### ISSUE TITLE
Overwriting a file keeps old tab open with old contents

### ISSUE THREAD

**Issue by emilyhuxng** [deephaven/web-client-ui#1017]
**Description**

After creating a file with a duplicate name and overwriting the file, the old tab will stay open and still contain the old contents.

**Steps to reproduce**

1. Go to file explorer and create a file.
2. Write some content into the file and save it.
3. Create another file and write some content.
4. Save it as the same name as the first file and overwrite it.

**Expected results**

Either change the old tab to an unsaved state and if you try to save it, force the user to change the name or close the old tab.

**Actual results**

Old tab stays open containing the old content. 

**Additional details and attachments**

https://user-images.githubusercontent.com/61912640/212344680-972bda8d-05e7-4ed2-afd2-51558a48b81d.mov

**Versions**

Engine Version: 0.19.1
Web UI Version: 0.25.0
Java Version: 17.0.5
Barrage Version: 0.5.0

**Comment by vbabich** [comment]
The behavior in Enterprise is close the old tab.
