### ISSUE TITLE
Expand all UI support for hierarchical tables

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1030]
The API will be supporting expand all in the future, and it would be nice to be able to expand all from the UI. Suggested methods:

- [ ] ctrl/cmd+click of the regular expand arrow/cell will expand all nested depths below the selected node
- [ ] (after filter section) _for rows that are expandable_ with two to four new menu options:
  - "Expand "Cell Value"" / "Collapse "Cell Value'"  - Expands or contracts the selected row, only show on expandable rows.
    Show the appropriate expand/collapse text based on if the row is collapsed or not. For "Cell value" insert the value of the cell 
    depth that would be expanded.
  - "Expand All in “Cell value”" - Expand all children of the selected row, only show option on expandable rows.
    Doesn't change to collapse if current row is expanded, as it may still have children that aren't expanded.
  - "Expand Entire Table" - expands all from root (if table is expandable, option should appear on all rows)
  - "Collapse Entire Table" - collapses all from root (if table is expandable, option should appear on all rows)

I think it would be useful for the context menu options on the whole row, not just the cell with the arrow.

Mockup: Note the truncating cell values, please set a max-width on them of 30ch
![image](https://user-images.githubusercontent.com/1576283/215613790-5c2b8ec9-173c-4b01-8946-caf18efee9c5.png)

**Comment by rcaudy** [comment]
+1 for:
>I think it would be useful for the context menu options on the whole row, not just the cell with the arrow right?

This feels like a faster, less fidgety UI, I think it's a good idea.

**Comment by mofojed** [comment]
Needs API implementation first, blocked by https://github.com/deephaven/deephaven-core/issues/3322

**Comment by emilyhuxng** [comment]
Could you explain "cell value"?

**Comment by dsmmcken** [comment]
Yeah, so if you right clicked "a3" in this example it would say:

![image](https://user-images.githubusercontent.com/1576283/215798698-b08dd4f5-71e9-482d-8282-cdc774612a1b.png)

"Expand "a3""

And if it has multiple level of nesting, and you were already at the second depth:

![image](https://user-images.githubusercontent.com/1576283/215799043-093a2768-f6de-4707-ad49-6f4e35720aae.png)

"Expand "d"" and so on.

**Comment by emilyhuxng** [comment]
![image](https://user-images.githubusercontent.com/61912640/215801718-6bfc11a8-34d8-463c-a12d-9507b1c95be8.png)
So what would it be in this example?

**Comment by dsmmcken** [comment]
Correct, you can think of it as the key that you are expanding at the current depth. So the first column at the first depth, second column at the second depth.

**Comment by emilyhuxng** [comment]
Could you paste the code snippet for your original example? I'd like to test on it.

**Comment by dsmmcken** [comment]
This is the query I use most often when monkeying around with stuff.

```
from deephaven import empty_table, time_table

simple_ticking = time_table("00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])

complex_ticking = simple_ticking.update([
        "MyBigDecimal= new java.math.BigDecimal(i+i/10)",
        "MyBigInteger= new java.math.BigInteger(Integer.toString(i))"
])                          

size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])

random_values_source = empty_table(10).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))"
])
```

**Comment by emilyhuxng** [comment]
Thanks! What about the "null" row for rollups? Should it be Expand "null"?

**Comment by dsmmcken** [comment]
Yes. We do something similar for the filter by menu btw:

![image](https://user-images.githubusercontent.com/1576283/215865569-1107a411-aec3-4bc8-bb32-4fc3ee436b13.png)
