### ISSUE TITLE
Columns hidden via layout_hint `hide` can't be toggled in the "Hide, Group, and Order Columns" menu

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1038]
**Steps to reproduce**
```
from deephaven import empty_table
t = empty_table(10).update(["X = i", "Y = i"]).layout_hints(hide=["Y"])
```
1. run the command above
2. open the table side bar menu by clicking the table sidebar overflow menu in the top right of the shown table
3. select the menu option "Hide, Group, and Order Columns"
4. attemp to toggle the hidden column by clicking the "eye" icon next to column `Y`

**Expected results**

Column `Y` can be shown or hidden with the eye, or show/hide all buttons.

**Actual results**

Eye does not toggle visibility of column, eye does not reflect current state of column. Additionally the "show all columns" context menu should also work to toggle this column, but it doesn't either.

The layout_hint should act as a hint to the initial state, not prevent it from changing states.

**Versions**

Engine Version: 0.20.0
Web UI Version: 0.26.0
Java Version: 11.0.16
Barrage Version: 0.5.0

**Comment by mattrunyon** [comment]
At least tangentially related to #526
