### ISSUE TITLE
Expandable rows shows have tooltip

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1061]
On rows that are expandable, tooltip expand cell with information that row can be clicked to be expanded, and ctrl/cmd clicked to expand row and all children.

Cursor should also be changed to reflect that it is clickable.

![image](https://user-images.githubusercontent.com/1576283/215615190-6fae3f48-ed9b-4156-83ce-a6708fd57624.png)

**Comment by emilyhuxng** [comment]
Should the tooltip appear anywhere on the row or only when the mouse is over the button?

**Comment by mofojed** [comment]
Should be whenever `GridRowTreeMouseHandler.isInTreeBox` is true.
