### ISSUE TITLE
Conditional Formatting errors when selecting color of timestamp column

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1091]
**Steps to reproduce**

1. Using a table with a timestamp column, select conditional formatting from the table sidebar options
2. Select the timestamp column/
3. DO NOT ENTER A VALUE
4. Select a style from the style drop down

**Expected results**

Nothing, formatting rule preview can't be applied with a value.

**Actual results**

Table errors, can't recover. Errors with timestamps, but strings are also incorrectly applying as undefined, and numbers as null. We shouldn't attempt to apply previews without a value.

Probably a bug introduced during the typescript conversion.

![image](https://user-images.githubusercontent.com/1576283/219454397-8da4b5ed-9ecf-432e-a43a-9521cadbb050.png)

**Versions**

Engine Version: 0.22.0
Web UI Version: 0.30.0
Java Version: 17.0.6
Barrage Version: 0.5.0

**Comment by bmingles** [comment]
@dsmmcken I think I have fixed the issue with Date columns. I am not seeing the string + number issue you mentioned 

> strings are also incorrectly applying as undefined, and numbers as null

**Comment by dsmmcken** [comment]
![image](https://user-images.githubusercontent.com/1576283/221218204-df6fc947-9305-4401-9de9-b6876ba93e56.png)

For strings: open a table, switch it to a double column, switch it to a string column, hit done.

I can't seem to replicate whatever issue I mentioned with numbers, so maybe I hallucinated that.
