### ISSUE TITLE
Conditional formatting should not be applied when set to "No Formatting

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1105]
**Steps to reproduce**

**Expected results**

**Actual results**

**Additional details and attachments**

**Versions**

 - Engine Version: ...
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by dsmmcken** [comment]
Duplicate #1106
