### ISSUE TITLE
Conditional column formatting - Undo applied style if query engine error occurs

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1121]
**Description**

If a conditional column condition + style are applied that results in a query engine error, the table gets into a non-recoverable state. 

**Steps to reproduce**

1. Create a ticking table with a DateTime column
```python
from deephaven import time_table

mylist = ["mars", "pluto", "saturn"]

simple_ticking = time_table("00:00:01").update([
    "Id=new Integer(i)",
    "Text=mylist[ (int) (3 * Math.random()) % 3 ]"
])
```

2 Apply a conditional style to a DateTime column with an `is` condition
3. Set the date value to "2020-01-01 America/New_York" (this can be parsed by UI but fails in query engine)

**Expected results**
The table should still be in a usable state. Ideally we can revert the last action on the undo stack or something comparable

**Actual results**
<img width="946" alt="image" src="https://user-images.githubusercontent.com/1900643/222255596-ab646beb-89bd-4ea2-8a15-001ce5e6f50c.png">

**Versions**

Engine Version: 0.22.0
Web UI Version: 0.30.1
Java Version: 17.0.6
Barrage Version: 0.5.0

**Comment by dsmmcken** [comment]
May not be necessary with #1130 as it won't  be as likely to occur.

**Comment by bmingles** [comment]
> May not be necessary with #1130 as it won't be as likely to occur.

@dsmmcken  It also occurs to me that the reproduction steps for this bug will likely no longer work after #1130 is done. There may be other use cases where we can get the table in an error state that can't recover, but it may actually prove impossible to get into the state from conditional formatting.

**Comment by dsmmcken** [comment]
Ok, closing then. Re-open if necessary.
