### ISSUE TITLE
FEATURE REQUEST: popout for panels (tables, plots, etc.)

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#1133]
As a user, I'd like the ability to pop a panel out of the console window into its own little popup window. A panel could be any of:

- table
- plot
- console
- notebook
- log
- maybe other things? I'm not sure.

There could be two ways to do it (note: Python syntax below, haven't considered what it would look like in Groovy):

Programatically: `table.popout(width, height)`, `plot.popout(width, height)`

Via the UI: in the options dropdown for any panel, add a `popout` option, maybe with an additional option to specify size? Or maybe size should only be customizable if done programatically. I'm not really sure.

Popout windows could be part of Deephaven layouts as well, for anyone who wants a Deephaven experience with some kind of starter layout.

**Comment by dsmmcken** [comment]
As in to a new browser window?

**Comment by jjbrosnan** [comment]
@dsmmcken Yes. A new window, if possible.

**Comment by vbabich** [comment]
Closing as WNI.
