### ISSUE TITLE
Freezing a tree table column crashes the panel

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1136]
**Description**

If you have a tree/rollup table, you can right click to freeze a column and the panel will break.

**Steps to reproduce**

1. Create a tree/rollup table
2. Right click a column header that isn't in the rollup grouped columns

**Expected results**

2. "Freeze column" disabled

**Actual results**

2. "Freeze column" is enabled, and clicking it breaks the panel because frozen columns is not implemented for tree tables

**Versions**

Engine Version: 0.22.0
Web UI Version: 0.31.1
Java Version: 17.0.6
Barrage Version: 0.5.0

**Comment by vbabich** [comment]
Double check that it also works in reverse - freeze then rollup.
