### ISSUE TITLE
UI for PartitionedTable

### ISSUE THREAD

**Issue by rcaudy** [deephaven/web-client-ui#1143]
As a user, it might be nice to display PartitionedTable objects in a friendly way. We could easily present a table grid of the non-constituent columns, for example, but that might be misleading to users without some visual cue that this isn't *just* a table, although it certainly is that.

@chipkent reports that we currently create a clickable icon, which may also be misleading.

**Comment by mofojed** [comment]
Related to multiple partition selector: https://github.com/deephaven/web-client-ui/issues/1438

And different types: https://github.com/deephaven/web-client-ui/issues/1441

**Comment by mofojed** [comment]
An example of a code snippet that produces a `PartitionedTable` (you must have `deephaven-plugin-plotly-express` installed):
```python
import deephaven.plot.express as dx
stocks = dx.data.stocks()
stocks_partitioned = stocks.partition_by(['sym', 'exchange'])
```

Just using the core deephaven libraries:
```python
from deephaven import empty_table
t = empty_table(10000).update(["x=(int)Math.floor(i/100)", "y=(int)Math.floor(i/10)", "z=i"])
pt = t.partition_by(["x", "y"])
```

The UI we're going to use is the [IrisGridPartitionSelector](https://github.com/deephaven/web-client-ui/blob/main/packages/iris-grid/src/IrisGridPartitionSelector.tsx), which will need support for multiple partitions added (#1438) and other types (#1441).

You can see the existing selector in action with parquet tables on #1414

**Comment by dsmmcken** [comment]
UI spec:
![image](https://github.com/deephaven/web-client-ui/assets/1576283/d427b993-1d09-43a5-960f-4e6cd0848f36)
