### ISSUE TITLE
Notebook mouse wheel and new LSP feature

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/web-client-ui#1191]
WRT https://github.com/deephaven/web-client-ui/pull/1178 in the context of a **notebook**:

When I've got a hover pop-up and I use the mouse wheel to scroll in the pop-up, everything works as expected (the mouse wheel action is confined to the limits of the pop-up).

When I'm typing and get a pop-up and I use the mouse wheel to scroll in the pop-up, the mouse wheel action effects the position of my notebook (causing the pop-up to move as well). This is not what I expect to happen. (Is this the "signatureHelp" feature?)

**Comment by mattrunyon** [comment]
Yes it was triggering on signatureHelp in what you showed me on the call

And on Firefox for Linux in case it is browser/OS dependent

**Comment by mattrunyon** [comment]
Reproduced on Chrome on Mac. The scrolling of the document happens when I am scrolling the popup past the top or bottom. Scrolling down when it's already at the bottom or up when it's already at the top

**Comment by dsmmcken** [comment]
Is this a monaco thing?

**Comment by mattrunyon** [comment]
Does not appear to be a bug with monaco when I tested on their playground. Monaco and VSCode both will dismiss the hover info and scroll the document if the hover modal has no scrolling. If it does, it will scroll the hover modal only
