### ISSUE TITLE
Add sideEffects to package.json to improve tree shaking

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1206]
Our code _should_ be tree shakeable since it's ESM; however, sometimes it is not detected as pure. One example is static class methods because they cannot be proven to be side-effect free. See [this issue](https://github.com/terser/terser/issues/724)

We should declare that our modules are side effect free by adding `sideEffect: false` or `sideEffect: ['*.css']` to our package.json files. Or we should see if we can publish our code in such a way that classes with static methods can be removed via tree shaking. See the latest comment about a TS spec to use define instead of set on static methods (I have no idea if this syntax is tree shakeable or not)

For an example, look at the dashboard-object-viewer plugin [here](https://unpkg.com/@deephaven/js-plugin-dashboard-object-viewer@0.2.0/dist/index.js). In the plugin you can search for `REGULAR_USER` which is part of `@deephaven/utils/TestUtils`. Not used at all in the plugin, but included b/c we use barrel imports (1 index file for each package) and it can't be definitively determined that the static method assignment does not have a side effect (unless we declare they don't).

As a test, I added `sideEffects: false` to all our package.json files and re-built the plugin. Dropped a few hundred kB in size and no more TestUtils in the bundle

For some reason it's not included in the code-studio bundle, so Vite may be doing more detection for source code compared to `node_modules` which is where the utils exist in the plugin

Another option/improvement would be to stop using classes w/ static methods to hold all of these methods. When they are imported, they are all included regardless of use. It does help some with namespacing though

**Comment by vbabich** [comment]
This should be done after de-globalizing jsapi
