### ISSUE TITLE
Bring jest up to root of lerna

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#122]
We can save resources running tests by using one common jest runner in the root web-client-ui dir instead of configuring it for each project:
Multiple project configs:
https://jestjs.io/docs/configuration#projects-arraystring--projectconfig

Using Jest with lerna:
https://github.com/facebook/jest/issues/3112#issuecomment-398581705

**Comment by mattrunyon** [comment]
Also might be a good idea to update the GitHub action to cache jest and only run tests with changed files since the PR base branch. Could make a new ticket for that too

**Comment by mofojed** [comment]
Should also implement Code Coverage reporting as an option
