### ISSUE TITLE
Right-click filtering should filter column to all values in selection, not just the row clicked

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1233]
When multiple rows are selected, right-clicking and using "filter by value" should filter based on **all** selected values, not only the row that was right-clicked.

This is how it looks now — I can only filter to one row, even though I selected three:

![image](https://user-images.githubusercontent.com/9516585/232843951-37325833-da8a-49a5-a560-01f8393f5bb5.png)

In the Swing UI, the dialog changes to "Filter by Value**s**", and allows you to filter based on multiple rows at once:

![image](https://user-images.githubusercontent.com/9516585/232844371-282c6909-ffd4-44b4-abe5-e114996a6e8c.png)

This is extremely useful when drilling into big tables (e.g. selecting a handful of stock ticker symbols to look at, or selecting a handful of ID numbers from some state log). It also makes it easy to filter to a subset of data so you can look at summary statistics from the column headers.

**Comment by dsmmcken** [comment]
Changes we want to make:

- [ ] Right-clicking on a row that isn’t selected should immediately change the selection to that row and present the menu options for that row
- [ ] Right-clicking inside an existing selection should present the filter by value menu based on the selection size. If there's only one selected row, it should function as it does currently. If there are multiple selected rows, it should present a "Filter by Values" (plural) menu. The preview at the top should show several values together to show that it is filtering by multiple values (although that may not be possible if the values are too long to show more than one). The UI will need to take a snapshot of the selection to get any values part of an offscreen selection. We should limit the snapshot to the first 1000 values or something as to not kill the client if the user has a whole table selected. For input tables where you might have multiple individual cells selected in different columns, use only the selected cells from the column that was clicked.


Display the number of rows selected below the values when there are multiple rows selected as shown:
![image](https://user-images.githubusercontent.com/1576283/233735293-fe597602-ad7d-49c8-b6ce-8425994ed1de.png)

**Comment by wusteven815** [comment]
A few questions regarding the filter's behaviour:
- What should happen when null is part of the selection range? For example, for strings, should it use the null menu or the string menu? If string menu, what would happen to with the "contains", "starts with", and "ends with" actions? (And similarly with numbers and those comparisons)
- What should the logic be with number comparisons? For example, if 1, 2, 3 are selected, what would the "greater than" comparison mean (>1 or >3)?

**Comment by dsmmcken** [comment]
1. If the user right clicks on a null value or boolean value directly, still show the null/boolean menus. It would be bad performance to snapshot and iterate client-side an entire selection before showing a menu. If the user wants a filter by all, they will need to click a non-null row.
2. For contains, starts with, ends with, remove null values when setting the filter. So if the selection was "a", "b", "c" and `null`, it should be just contains a, b, c. To be clear, equals/not equals should be ORs and contains/starts with/ends with should be ANDs
3. Logic for numbers same as strings. OR for equal/not equals, AND for everything else.

I think that makes sense.
