### ISSUE TITLE
Add provenance to published npm packages

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1235]
see: https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/

Not sure if lerna publish supports the flag or not.

**Comment by mattrunyon** [comment]
I think it should be doable via [npm-client-args flag](https://github.com/lerna/lerna/tree/main/libs/commands/version#--npm-client-args)

**Comment by mofojed** [comment]
Provenance is not supported in lerna right now: https://github.com/lerna/lerna/issues/3657
Says at the bottom of https://docs.npmjs.com/generating-provenance-statements:
> Note: At this time, lerna and yarn are not supported tools for publishing your packages with provenance.

**Comment by JamesHenry** [comment]
FYI https://github.com/lerna/lerna/issues/3657#issuecomment-1535284598

**Comment by mofojed** [comment]
Awesome, thanks @JamesHenry !
