### ISSUE TITLE
Confusing quick filter behavior around string column "null"

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/web-client-ui#1243]
I'm unable to do a literal search for the string "null" using the string "null" in the web UI quick filter - it assumes I want to search for the `null` value. This is due to an implementation detail in `io.deephaven.engine.table.impl.select.MatchFilter` when using `MatchFilter#strValues`:

```java
Object convertStringLiteral(String str) {
    if (str.equals("null")) {
        return null;
    }
    ...
}
```

It may be that this is "as-desired", but it's a potential gotcha as it's different than every other string.

![image](https://user-images.githubusercontent.com/6764691/233700184-c5919288-f5d9-464a-a237-5b22010a22fe.png)

I see the importance of wanting to filter to `null` values, but I wonder if there might be a better way to expose this functionality? I wonder if an explicit option "is null" would be better? (This could also be a good place to introduce an "is empty" filter.)

I'm able to workaround this issue by going to advanced filters and explicitly selecting the "null" value.

![image](https://user-images.githubusercontent.com/6764691/233701468-010997df-288d-42b7-8af4-9023f78306f1.png)

As another note, the values in the advanced filters box might want to use the text rendering that the grid cell uses, so the user can tell the difference between `null` and "".

**Comment by devinrsmith** [comment]
Don noted a workaround, using the literal `\null` or `=null`, which seems to correctly search for the string "null". `\` also works for literal empty (but `=` does not).

**Comment by dsmmcken** [comment]
typing `=` errors as invalid, but selecting context menu "filter by value" on empty fills the quick filter bar with just = as value and does work. So we should probably make that consistent.

**Comment by dsmmcken** [comment]
From slack:

Bender
>Maybe we should have some sort of visual indicator when you enter null that it's searching for null instead of "null"? I dunno how we show that though

donmckenzie
>yeah, present it similar to how it is in the table with italics?
