### ISSUE TITLE
Prompt to save or discard when refreshing layout in IDE

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/web-client-ui#1250]
When you're writing a Python script in the DH IDE, refreshing the layout causes you to lose the script if it has not been saved. The "refresh layout" command should prompt the user to either save or discard their scripts. 

**Steps to reproduce**

1. Go into the IDE
2. Write a Python script
3. Do not save Python script
4. Refresh layout

**Expected results**

Would like to see a prompt to save or discard script.

**Actual results**

Script goes away. Sad :(

**Versions**

 - Engine Version: 0.23.0
 - Web UI Version: 0.37.1
 - OS: MacOS Ventura
 - Browser: Safari

**Comment by dsmmcken** [comment]
Just confirming, you mean this button right?

![image](https://user-images.githubusercontent.com/1576283/234400858-3a53c195-075b-4163-9cd8-1904fc57287b.png)
