### ISSUE TITLE
Typing "Db<tab>" as a table name in CommunityIntegration forces to lowercase

### ISSUE THREAD

**Issue by rachelmbrubaker** [deephaven/web-client-ui#1251]
**Description**

It appears this comes from "db" being in the binding, therefore it is selected as a variable name, and overrides the casing the has typed in.

**Steps to reproduce**

Context: DnD, groovy, silverheels, autocomplete 
Start typing a commonly-used query in a console `pel = db.iiveTable("DbInternal", "ProcessEventLog").where("Date=currentDateNy()")`

After typing `pel = db.i("Db"` press tab to prompt autocomplete (cursor should be before the last quote).

https://user-images.githubusercontent.com/84355699/234416231-6afbe9cb-a992-412c-8067-d22350485426.mov

**Expected results**

No change to an appropriately-cased input as typed by the user.

**Actual results**

In this case it makes “Db” go lowercase to “db”. 

**Additional details and attachments**

 “DbI” then `<tab>` has no effect. This seems to match up with the idea that it is the variable in the binding causing this.

The simplest solution (if the timeframe can line up) could be the implementation of https://deephaven.atlassian.net/browse/DH-14362

Once the server/engine is returning a list of GetCompletionItems, that will override whatever is already there (i.e. the current variables in the binding).

**Versions**
DHE Versions=1.20230131.129 and 0.21.1

**Comment by mattrunyon** [comment]
We can disable word based suggestions in Monaco which is what is happening here. If the server does not respond with any autocomplete suggestions, Monaco is defaulting to word based so in this case since the line contains `db.` it suggests `db` as a valid option

https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IGlobalEditorOptions.html#wordBasedSuggestions

**Comment by JamesXNelson** [comment]
ya, if the suggestions are coming from monaco itself, disabling word suggestions is the only option.

It may also be worth it to always have the server respond w/ an autocomplete of "change nothing".  i.e. default autocomplete option is "keep it the same", and give it a high priority. This might trick things enough that `db<tab>` would just emit `db`.  Matt idea sounds like a decent choice.  I know the builtin guessing it does helps to reuse tokens we have seen inside of strings, but we could just make our own completer do something similar to replace the builtin.

**Comment by mattrunyon** [comment]
Followed up w/ Rachel. DnD autocomplete has some support for PQ table names now, so this is in an acceptable state. We could consider disabling word completion (default/fallback in monaco) in the future, but closing for now
