### ISSUE TITLE
Add uncaught errors to support logs

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1253]
Right now, if the JS API throws an error, it might be uncaught and those don't seem to get added to the support logs because they bypass `console.error`. We should probably add a window level listener for uncaught errors and add them to the support logs

**Comment by mofojed** [comment]
Details on adding a window level listener for unhandled promise rejections: https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event
And for error events: https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event
Note that `LogProxy` already handles uncaught errors, so we just need to add the unhandled rejections listener similarly.
