### ISSUE TITLE
Add Contains Ignore Case option to Seek Row functionality

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1274]
We currently have Seek Row functionality in grids for searching for text within a column. There are only a few options there, we should add the Contains Ignore Case option as well.

![image](https://user-images.githubusercontent.com/4505624/236909107-2e9b08ab-a38c-48e2-a7c9-3b31a3248ada.png)

Context: https://illumon.slack.com/archives/CAUG7MC2D/p1683398883944149

**Comment by dsmmcken** [comment]
These should use human labels -- "Equals (ignore case)" or whatever we've done elsewhere.

**Comment by mofojed** [comment]
@ethanalvizo you can create a table with a string column to test this feature. From our docs (https://deephaven.io/core/docs/reference/table-operations/create/stringCol/):

```
from deephaven import new_table
from deephaven.column import string_col

result = new_table([
    string_col("x", ["Deephaven", "DEEPHAVEN", "deephaven", "illumon", "ILLUMON"])
])
```
Then in the table that appears, open the [table sidebar](https://deephaven.io/core/docs/how-to-guides/user-interface/work-with-rows/#table-options-menu) and click the "Go to" option to display the Go to feature:
![image](https://github.com/deephaven/web-client-ui/assets/4505624/acb21436-a7c6-44f9-ab5b-5043e8716883)
