### ISSUE TITLE
Add end-to-end tests for all table sidebar operations

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1295]
We recently had a bug where Select Distinct functionality was broken: https://github.com/deephaven/web-client-ui/issues/1275

We should have end-to-end (e2e) tests in Playwright that test all the functionality in the table sidebar, so we reduce the chances of regressions in our core functionality.

- [x] #1315
- [x] #1316
- [x] #1332
- [x] #1344
- [x] #1345
- [x] #1305
- [x] Download CSV
- [x] #1356
- [x] Quick Filters
- [x] #1313
- [x] Go to
- [x] Chart Builder (we don't need to do at this time, as we will restructure the chart builder)

**Comment by ethanalvizo** [comment]
Conditional Formatting is too flaky because of no loading status #1367.
Custom Columns drag step is inconsistent on webkit #1360

**Comment by ethanalvizo** [comment]
Marking this as complete. The e2e tests with bugs are already filed on separate tickets
