### ISSUE TITLE
e2e snapshots should be linux only

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1331]
Remove any windows/mac (darwin) e2e snapshots and ignore any future snapshots from being added. CI runs in a linux container, and local snapshots can only correctly isolated and generated inside the Linux docker container.

**Comment by mofojed** [comment]
We should remove `e2e:update-snapshots` script from package.json, and rename `e2e:update-ci-snapshots` to `e2e:update-snapshots`. Using local OS specific snapshots should just be for debugging.
Also need to delete all existing `darwin` and/or `windows` snapshots.

**Comment by mattrunyon** [comment]
Also add a gitignore to the test folder with something like

```
*-snapshots/*
!*-snapshots/*-linux*
```

**Comment by ethanalvizo** [comment]
Resolved by #1350
