### ISSUE TITLE
Aggregate Columns ignores columns selection

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1355]
**Description**

![image](https://github.com/deephaven/web-client-ui/assets/1576283/b994a588-ba89-4837-9960-ca62b0165666)

**Steps to reproduce**

Using the following table:
```
from deephaven import empty_table, time_table

simple_ticking = time_table("PT00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])

complex_ticking = simple_ticking.update([
        "MyBigDecimal= new java.math.BigDecimal(i+i/10)",
        "MyBigInteger= new java.math.BigInteger(Integer.toString(i))"
])                          
```
1. select from table options sidebar "Aggregate Columns"
2. Select sum from drop down and click add aggregation
3. From the sum button click the pencil to edit aggregations
4. De-select a number of columns

**Expected results**

Sum is only computed for the selected columns

**Actual results**

Sum is selected for all columns

**Versions**
Vermillion and 

Engine Version: 0.26.0
Web UI Version: 0.40.4
Java Version: 17.0.7
Barrage Version: 0.5.0

**Comment by vbabich** [comment]
@niloc132 will add the `SKIP` operation and the UI will need to set that as a default.

**Comment by niloc132** [comment]
Is there a dhc issue for this? I'm not finding one...

**Comment by mofojed** [comment]
@niloc132 Would need to split off one for core

**Comment by mofojed** [comment]
@niloc132 finally created one for core: https://github.com/deephaven/deephaven-core/issues/4182
