### ISSUE TITLE
layout_hint search_display_mode isn't honoured

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1358]
**Description**

doc strings describe a search_display_mode parameter for layout_hints, but it has no effect.

**Steps to reproduce**
```
from deephaven import empty_table, time_table
from deephaven.table import SearchDisplayMode

size = 100
scale = 1000


random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? i%2==0 ? i%3==0? `null` : `` :  null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])


layout_hints_example = random_values_with_null_NaN.layout_hints(
    search_display_mode=SearchDisplayMode.SHOW
)
```

**Expected results**

search bar is shown

**Actual results**

search bar is not shown

**Versions**
Engine Version: 0.26.0
Web UI Version: 0.40.4
Java Version: 17.0.7
Barrage Version: 0.5.0

**Comment by mofojed** [comment]
I added support for the search display modes on the server: https://github.com/deephaven/deephaven-core/pull/3512

Something not wired up correctly? I could've sworn I tested this, though my PR description indicates I only tested that you _could_ bring up the search bar, not that it was up by default.

**Comment by mofojed** [comment]
This is working as originally designed. See the Enterprise docs for search access: https://deephaven.io/enterprise/docs/formatting/search-access/
`SearchDisplayMode.SHOW` just means that we show the option to show the search bar; not that it is shown by default. Perhaps the latter is something we want, but that's not what that flag is defined to do, so we'd want a different flag.
