### ISSUE TITLE
Copy/Rename/Delete are missing from notebook menu options

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1359]
Enterprise notebooks expose Copy/Rename/Delete on the notebook overflow menu dropdown, these options are missing in community.

![image](https://github.com/deephaven/web-client-ui/assets/1576283/44bc8aed-1075-4347-b4f4-6651863c7870)

**Versions**
Engine Version: 0.26.0
Web UI Version: 0.40.4
Java Version: 17.0.7
Barrage Version: 0.5.0

**Comment by georgecwan** [comment]
If Delete is included in the overflow menu dropdown, should it also be included in the context menu that appears on right clicking the tab? It currently has copy and rename but not delete.
<img width="203" alt="image" src="https://github.com/deephaven/web-client-ui/assets/57882714/18533457-35b4-4468-81bd-fd5efc6febf8">
