### ISSUE TITLE
Conditional format e2e test is flaky

### ISSUE THREAD

**Issue by ethanalvizo** [deephaven/web-client-ui#1367]
**Description**

The snapshot comparisons for the conditional format e2e test in `table-operations.spec.ts` are flaky. I suspect this is due to the conditional format operation not triggering the loading status bar the same way the other table operations do. Because we can't check for this loading status bar in the tests the snapshot comparisons happen too quickly.

**Steps to reproduce**
1. `npm run e2e:update-ci-snapshots`
2.  Make sure no new snapshots are regenerated
3. Push to github and the CI pipeline should fail

**Expected results**
No new snapshots generated locally after running the command on step 1 and Github pipeline passes

**Actual results**
[0d7d73aedda25dcc77be4215946ed6b5cad55830.webm](https://github.com/deephaven/web-client-ui/assets/55671206/3f75ff09-bdab-429b-a057-4592dc674aa5)

**Additional details and attachments**

**Comment by mofojed** [comment]
Seems to have been resolved with refactors of the e2e tests
