### ISSUE TITLE
Rename File Explorer "Copy" action to "Copy file"

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1375]
In the file explorer, if you right click on a notebook, there is a "Copy" button. That is actually "Make a Copy" or just  "Make Copy". I expected "Copy" to then let me paste it somewhere

Google Drive has a "Make a Copy" button which has the same behavior as ours. Creates a copy and names it w/ "Copy of" preceding the file name. We append "-1" to the file name, so similar behavior

**Comment by dsmmcken** [comment]
Would prefer it to start with the word copy.

"Copy file" ?

**Comment by mattrunyon** [comment]
Not sure. It just didn't do what I expected

I think this also might be an enterprise only issue? I don't even see a copy button in community, just delete and rename

**Comment by tarunsamanta2k20** [comment]
Can I work on it?

**Comment by tarunsamanta2k20** [comment]
@vbabich i am getting this error while running the app.

![image](https://github.com/deephaven/web-client-ui/assets/55488549/50d9a96b-2a0f-46f6-84c6-3483a5b324cb)

**Comment by vbabich** [comment]
@tarunsamanta2k20 This repository (web-client-ui) contains the UI side of Deephaven. To run the whole thing locally you'll need to install the server side as well, https://github.com/deephaven/deephaven-core

**Comment by GcWan** [comment]
The copy action is only available on the Enterprise product, not the Community version. Spun this issue off into #1488.
