### ISSUE TITLE
Context menu for console input not working

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#139]
**Description**

Right click on the console input bar. Monaco menu immediately opens/and closes instantly.

**Versions**
 - Deephaven: 0.2.0

**Comment by mofojed** [comment]
I'm not able to reproduce this issue - @dsmmcken if you can still reproduce it please include more details (OS/Browser, any other steps taken).

**Comment by mofojed** [comment]
This seems to only be reproducible on the Enterprise side, logged Enterprise ticket to track: https://deephaven.atlassian.net/browse/DH-11499
