### ISSUE TITLE
Auto-reload of default layouts

### ISSUE THREAD

**Issue by kzk2000** [deephaven/web-client-ui#1396]
When a user goes to the DH UI, and clicks around, the browser caches the latest arrangements of all tabs and charts.

Would it be possible to add a default behavior such that upon EACH UI reload in the browser, it would revert back to the default layout and NOT use that user's local browser cache.

**Use case:** Creation of DH dashboards with the OSS version that force reload the layouts each time a user re-opens it.

**Comment by dsmmcken** [comment]
I guess we could extend the layout json with a flag to prevent generating a local dashboard overrides, and in future it be a part of a programmatic layout definition.

Would probably also be worth looking into an even more locked down and non-rearrangeable dashboard option, combined with locking down table interactions.

**Comment by dsmmcken** [comment]
Closing in favor of ui.dashboard https://github.com/deephaven/deephaven-plugins/issues/61
