### ISSUE TITLE
Tree and rollup tables are not sortable

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1402]
**Description**

After #1390 tree and rollup tables are not sortable.

The definition added to `IrisGridTableModel` should be in `IrisGridTableModelTemplate` because `IrisGridTreeTableModel` is using the default implementation which just always returns false.

We should also change the default to true probably since the engine should just fail the sort and tell the UI in those cases. According to [this comment](https://github.com/deephaven/deephaven-core/issues/1914#issuecomment-1028294907), the bug where the error was thrown instead of reported as a message to the UI is fixed, so should be fine to default to let the user try to sort (although the default implementation in `IrisGridModel` won't be hit in our uses)

**Steps to reproduce**

1. Create a tree or rollup table.
2. Try to sort a column that you would normally be able to sort

**Expected results**

3. Column sorts

**Actual results**

3. Column is not sortable in the UI

**Versions**

 - Engine Version: 0.26.0
 - Web UI Version: 0.44.0

**Comment by dsmmcken** [comment]
>  so should be fine to default to let the user try to sort

The point of marking columns as not sortable is that we can communicate that to the user if something is not sortable and disable the various ways to sort rather than just not do it. We should expect columns to be explicit from now on.

**Comment by mattrunyon** [comment]
In cases where the API does not report if a column is sortable, I'm saying we should probably default to true (which this currently does, just not for tree tables). That is the least breaking path since before we said everything was sortable. Otherwise we will break enterprise until they implement the API (if they implement it even)
