### ISSUE TITLE
Go to row panel should update the row number as you navigate the selection

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1406]
As you navigate the selection, the row number in the `Go to row` panel should change.

![image (20)](https://github.com/deephaven/web-client-ui/assets/2853653/04cb89f4-4d8b-4b4c-9385-2c3546c0ed2c)

**Comment by vbabich** [comment]
Use `cursorRow` for the input value, since there can be more than one row selected.

**Comment by mofojed** [comment]
Steps to Reproduce in DHC:
1. Create a table with many rows, e.g.:
```
from deephaven import empty_table
t = empty_table(1000).update("x=i")
```
2. In the table, open up the "Go to Row" view (sidebar menu -> Go To)
3. Click in the table to move selection

Expected Results:
3. Row number updates in the Go to row view

Actual Results:
3. Row number does not update
