### ISSUE TITLE
Number of rows is counting totals table rows in total

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1407]
**Description**

![image](https://github.com/deephaven/web-client-ui/assets/1576283/64221720-a194-40dc-9b2b-bbfbaadf7343)

**Steps to reproduce**

1. create a static table with known number of rows 
    ```
    from deephaven import empty_table
    t = empty_table(1).update("x = i")
    ```
2. note the number of rows you have (1)
3. go to  "Aggregate Columns" from the table sidebar and add any aggregation
4. hover the table or column tooltip

**Expected results**

Shows number of rows as 1.

**Actual results**

Shows number of rows as 2, because it includes the totals table row.

**Versions**

Engine Version: 0.27.0
Web UI Version: 0.44.1
Java Version: 11.0.19
Barrage Version: 0.6.0

**Comment by mofojed** [comment]
Previously we removed the pending row count: https://github.com/deephaven/web-client-ui/pull/916
We just need to remove the totals row count as well.
