### ISSUE TITLE
Explicit return type not required in TypeScript anymore

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1413]
**Description**

Not sure when this changed, but we used to enforce an explicit return type. We're no longer doing that, and we should re-enable enforcing it it.

**Steps to reproduce**
1. In the code, remove the return type from a function

**Expected results**
1. Linter should fail, requiring a return type to be specified

**Actual results**
1. Linter does not fail

**Comment by mattrunyon** [comment]
I think previously one of the configs we extended had [explicit-module-boundary-types](https://typescript-eslint.io/rules/explicit-module-boundary-types/) enabled. This is for anything exported and the benefit is it makes it more clear if a change was made to a potentially public facing API

There is also [explicit-function-return-type](https://typescript-eslint.io/rules/explicit-function-return-type/) which I don't think we had enabled. This requires it for all functions, even if they are not exported
