### ISSUE TITLE
Various issues with keyboard shortcuts. 

### ISSUE THREAD

**Issue by aosecky** [deephaven/web-client-ui#142]
**Description**

Some of the expected keyboard shortcuts are not working as expected. 
These manifest differently between windows and macos. 

I found these on Deephaven Enterprise but will effect OSS as well. 

**Windows**
Ctrl + L 
Expected clear console. Actually brings up linking tool. 

Ctrl + H  when history tab is not active
Expected history tab becomes active and gets focus. Actually nothing happens. 

Delete when file explorer tab is active
Expected delete notebook dialog. Actually delete command is entered into currently active notebook. 

Enter when file explorer tab is active
Expected change name dialog. Actually enter command is entered into currently active notebook. 

Ctrl + S on Input Table
Expected commit changes. Actually brings up search bar. 

Ctrl + E
Expected clear all table filters on all tables. Actually moves focus to title bar.

**MacOs**

Control + C
Expected clearing console history. Actually nothing happens. 

Cmd + Shift + E
Expected clearing filters on currently active table. Actually all filters on all tables are cleared. 

Cmd + S on Input table
Expected to commit input table changes. Actually toggles search bar. 

Cmd + E 
Expected clear all table filters on all tables. Actually highlights Edit but no action is preformed. 

**Versions**
 - Deephaven Enterprise: 1.20210201.147beta
 - Web Browser: crhome

**Comment by mattrunyon** [comment]
Windows
Ctrl + L
Now clears console input

Ctrl + H when history tab is not active
Working as expected

Delete when file explorer tab is active
This one is tricky and requires some more changes to function better. Opened #151 to address file explorer issues

Enter when file explorer tab is active
Same as above.

Ctrl + S on Input Table
Should commit changes now. Ctrl+shift+F is search now for input tables.

Ctrl + E
Clears table filters for all tables.

MacOs

Control + C
Clears console input, not history.

Cmd + Shift + E
Clears filters on active table only

Cmd + S on Input table
Commits changes. Cmd+Shift+F is search now.

Cmd + E
Clears filters on all open tables
