### ISSUE TITLE
Table export should preserve data rather than reflecting the UI text content

### ISSUE THREAD

**Issue by niloc132** [deephaven/web-client-ui#1433]
(Marked as a feature request, but I'd suggest this is actually a bug, will leave it to you to decide)

As a table-viewing user, when I export a table to CSV with Instant columns, they should not lose the date component of the instant (and thus become LocalTime). Instead, the exported CSV should have the data that was present in the table, not just what was visible at the time. This way, when re-importing the file as a new table, the data should be as close as possible to what was in the original table.

**Comment by dsmmcken** [comment]
It is intentionally WYSIWYG. 

If you want the raw values check the unformatted values checkmark before downloading, or format your columns to show the date with the timestamp.

![image](https://github.com/deephaven/web-client-ui/assets/1576283/65d1f88d-5be7-4f1b-b300-fd9da693ed21)

**Comment by niloc132** [comment]
Good to know, I think we have some test cases that validate that we can round trip data that are showing up as broken (DHC doesn't have a flight encoder for LocalTime implemented) that DHE seems to be successful for, but practically DHE changes types and loses precision so isn't round tripping either.
