### ISSUE TITLE
Closing tab with middle mouse button pastes into active monaco editor

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1461]
**Description**

If a monaco editor is active, closing a golden layout panel with middle mouse button also pastes your clipboard into the active monaco editor.

**Steps to reproduce**

1. Open a notebook/table
2. Focus a monaco editor like the console
3. Middle click on an open tab to close it

**Expected results**

4. Panel closes.

**Actual results**

4. Panel closes and clipboard pastes to monaco

**Versions**

 - Web UI Version: 0.46.0
 - OS: Pop OS (Ubuntu 22.04 based)
 - Browser: Chromium 116.0.5845.96

**Comment by dsmmcken** [comment]
video/gif? I can't reproduce.

**Comment by mattrunyon** [comment]
https://github.com/deephaven/web-client-ui/assets/8619789/e9e9ce2c-2540-497a-b92a-1ea0e807279a

It might be linux specific. In the video I just middle clicked on the tab with monaco focused

**Comment by dsmmcken** [comment]
https://github.com/deephaven/web-client-ui/issues/552

**Comment by mofojed** [comment]
I can attest it is still a problem even though I can also attest that I have fixed it before. Seems to be Ubuntu specific?
