### ISSUE TITLE
Incompatible charts are rendered without error/warning

### ISSUE THREAD

**Issue by niloc132** [deephaven/web-client-ui#1462]
**Description**

The deephaven-core plotting API has a complex history, resulting in some configurations which are not supported by the JS API and web clients. However, the gRPC and JS APIs expose errors that are reported due to such states to the UI, and the UI should report to the user that the current configuration will not behave as expected.

**Steps to reproduce**

**Expected results**
An error message should be displayed, something to the effect of "OpenAPI presently does not support series of type io.deephaven.plot.datasets.multiseries.MultiXYSeriesSwappable"

**Actual results**

No error/warning, but the plot appears to never load

**Comment by bmingles** [comment]
@niloc132 Do you have reproduction steps example for a config that should cause this message?

**Comment by mofojed** [comment]
Fixed with https://github.com/deephaven/web-client-ui/pull/1614
