### ISSUE TITLE
Table Cell Link is Clickable Through the View Full Contents Icon

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/web-client-ui#1480]
**Description**

If a long string is truncated to fit into a grid cell and the "view full contents" icon overlaps a link, then the link can be clicked through the icon.

**Steps to reproduce**

```groovy
import io.deephaven.engine.util.TableTools
t = TableTools.emptyTable(1).updateView("X = `Some front text: http://www.google.com some trailing text`", "Y = 0")
```

Then shrink column `X` by sliding `Y` over until the icon overlaps the link.

**Expected results**

Ideally clicking the icon stops the mouse event from falling through to the link.

**Actual results**

If I click low or click high, I can open the cell contents. However, if I click in the middle of the icon it opens the link in a new tab.

<img width="293" alt="Screenshot 2023-09-03 at 5 12 13 PM" src="https://github.com/deephaven/web-client-ui/assets/1030443/3f795b65-a424-4766-b879-34d4c89b0e0b">

**Versions**

Web UI Version: [v0.46.1](https://github.com/deephaven/web-client-ui/commit/c24d1911aa97d13ece3bebfae41b9ec75f33f580)

**Comment by mofojed** [comment]
Should just need to update the priority of the mouse handlers so that overflow handler has priority over GridTokenMouseHandler: https://github.com/deephaven/web-client-ui/blob/d15d6b1d174acd77c63c2dfc28a49ca08a4cd0ab/packages/iris-grid/src/mousehandlers/IrisGridCellOverflowMouseHandler.ts#L18
Though there may be more to it...

**Comment by mofojed** [comment]
A snippet for python:
```python
from deephaven import empty_table
t = empty_table(1).update_view(["X = `Some front text: http://www.google.com some trailing text`", "Y = 0"])
```
