### ISSUE TITLE
Rollup grouping columns shouldn't show as 'null'

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1483]
The key columns for a rollup in the UI shouldn't show `null` for a rolled-up key — it would be better to show completely blank cells or details of the key columns (e.g. a count of values/the themselves if they'd fit).

![image](https://github.com/deephaven/web-client-ui/assets/9516585/a1b51e42-a0a0-4f8e-aa4e-2bd004c171c8)

We could also allow right-clicking to show all the values (or all of the complete keys).

**Comment by mattrunyon** [comment]
This formatting is for string columns so users can differentiate between null value, empty string (shows as stylized empty) and a string containing only non-printable characters or whitespace. See DH-12038

**Comment by rbasralian** [comment]
While that is desirable for regular tables (where we genuinely expect to see both empty strings and nulls), in the rolled-up key columns of a rollup it doesn't really help us (since there will never be a valid individual value there).

**Comment by mofojed** [comment]
We should be able to handle showing an empty cell instead of null specifically for key columns of rollups fairly easily in our IrisGridTreeTableModel.

**Comment by mofojed** [comment]
You can use the rollup from our core docs example to get this issue:
```python
from deephaven import read_csv, agg

insurance = read_csv("https://media.githubusercontent.com/media/deephaven/examples/main/Insurance/csv/insurance.csv")

agg_list = [agg.avg(cols=["bmi", "expenses"])]
by_list = ["region", "age"]

test_rollup = insurance.rollup(aggs=None, by=by_list, include_constituents=True)
insurance_rollup = insurance.rollup(aggs=agg_list, by=by_list, include_constituents=True)
```
![image](https://github.com/deephaven/web-client-ui/assets/4505624/dc6deb48-e903-4a9f-b970-e93b10027727)

Still need to make sure a regular table with empty and null appear correctly:
```
from deephaven import empty_table, time_table

size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? null : `a`+(int)(scale*(Math.random()*2-1)))"
])
```
