### ISSUE TITLE
Add "Copy File" action to File Explorer

### ISSUE THREAD

**Issue by GcWan** [deephaven/web-client-ui#1488]
As a user, I would like a way to create a copy of a file inside the file explorer. Currently, right clicking a file in the file explorer only gives the "Delete" and "Rename" actions. There is no way to make a duplicate of a file in the file explorer outside of copy and pasting the contents of the file itself. I would like a "Copy File" option to be added so that files can be duplicated inside the file explorer by selecting the action from the right click menu.

**Comment by dsmmcken** [comment]
Coincidently, I happened to be working on something near this code and started a fix for it already. Assigning to self.
