### ISSUE TITLE
Add Enable/Disable Checkbox for Individual Formatting Rules

### ISSUE THREAD

**Issue by Zhou-Ziheng** [deephaven/web-client-ui#1536]
As a user, I want an Enable/Disable button for each formatting rule so that I can temporary disable a formatting rule without having to completely remove it and recreate it.

**Comment by dsmmcken** [comment]
Which formatting rules are you referring to?

**Comment by Zhou-Ziheng** [comment]
![image](https://github.com/deephaven/web-client-ui/assets/75397821/7a72e57e-d66c-4774-9e22-bfcdfd7a7dee)
