### ISSUE TITLE
Use conventionalcommits changelog preset

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1566]
Apparently lerna uses the `angular` changelog preset by default. We should be using the `conventionalcommits` preset, so that we can add an exclamation mark after type. Currently you cannot put an exclamation mark after the type (as noted in our CONTRIBUTING guide) or things will blow up when you try to version it. According to this lerna issue, it's because we're using the wrong preset: https://github.com/lerna/lerna/issues/2668#issuecomment-708632441

However I tried to create a PR for doing exactly that: https://github.com/deephaven/web-client-ui/pull/1565

But it just hangs on the versioning step. Logging this ticket to record the information, and then I'm going to forget about it for now.

**Comment by vbabich** [comment]
Won't fix
