### ISSUE TITLE
Spacing issue on chart panel tooltip

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1569]
**Description**

The panel tooltip for `ChartPanel` has a spacing issue. This is apparent on both the DH plotting charts and plotly express charts (which just renders a `ChartPanel`)

![image](https://github.com/deephaven/web-client-ui/assets/8619789/955286c3-2486-4ff1-afa5-b05a3386e81b)

![image](https://github.com/deephaven/web-client-ui/assets/8619789/79c5897c-48dc-477a-844d-250c1e6ceb89)

**Steps to reproduce**

1. Create a chart
2. Hover the tab of the chart to get the tooltip

**Expected results**

3. Properly spaced tooltip

**Actual results**

3. Improperly spaced tooltips

**Versions**

 - Web UI Version: 0.49.1

**Comment by vbabich** [comment]
Will be refactored in widget changes/deephaven.ui.

**Comment by mattrunyon** [comment]
Should we leave this and the other chart issue open until they're recfactored then? I don't think they will be fixed by a refactor necessarily.
