### ISSUE TITLE
Resizing log window does not reflow log messages

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#158]
**Description**

![image](https://user-images.githubusercontent.com/8619789/129399592-83623ff8-10bb-460f-90a6-9b728844f630.png)

Resizing the log window does not reflow log messages. As a result, they go under the scroll bar

**Steps to reproduce**
1. Open the log tab
2. Shrink the tab until a message would go under the scroll bar

**Expected results**

Messages reflow on resize so they do not become hidden under the scroll bar

**Actual results**

Messages do not reflow and become hidden under the scroll bar. Also, the scroll bar is transparent so it looks wrong

**Versions**
 - Deephaven: 0.2.1

**Comment by mofojed** [comment]
@mattrunyon I'm unable to reproduce this on `59deee2c`, is this still reproducible for you?

**Comment by mattrunyon** [comment]
Can't reproduce in 0.3.1. Reproduced in 0.2.1, so it must have been fixed by something in between
