### ISSUE TITLE
Monaco autocomplete colors are incorrect

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1592]
`--dh-color-editor-suggest-fg` should be `--dh-color-white`. Right now we end up w/ black on gray text.

![image](https://github.com/deephaven/web-client-ui/assets/8619789/55f52874-9e0d-43d9-896f-a36ae5b5f487)

We should also probably add a variable to set `--vscode-editorSuggestWidget-selectedForeground` to `--dh-color-white` as well. It is currently set to `#ffffff` by monaco. This affects the color of the non-matching portion when there is keyboard selection on an autocomplete item.

Might want to set something for the blue colors used in selected/non-selected suggestions as well. Those are `--vscode-editorSuggestWidget-highlightForeground` and `--vscode-editorSuggestWidget-focusHighlightForeground`

**Versions**

 - Web UI Version: 0.50.0

**Comment by bmingles** [comment]
Found a "complete" list of Monaco theme variables in an old PR
https://github.com/microsoft/monaco-editor/issues/2622#issuecomment-903632722
