### ISSUE TITLE
"Copy tab name to clipboard" option

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1595]
It would be great to be able to copy the title of a tab in the UI (or its underlying table variable's name). It's helpful when working on a query in a code studio with tables with long names. Example:

![image](https://github.com/deephaven/web-client-ui/assets/9516585/40eda7fb-9833-48bb-9b64-804ca12bd63b)

Swing:

![image](https://github.com/deephaven/web-client-ui/assets/9516585/da5366f6-d96b-4338-b3d1-6ced59229cc1)

**Comment by dsmmcken** [comment]
This feature was added already in a previous version. It's in both the context menu and as button in the tab tooltip.
![image](https://github.com/deephaven/web-client-ui/assets/1576283/93816c2c-1492-4894-afdb-2978d4721d0a)
![image](https://github.com/deephaven/web-client-ui/assets/1576283/5f555eec-1d3b-4281-9257-820f44508c14)

Note: some of the newer widgets don't have the proper name displayed for copying yet (deephaven.ui panels etc) #1570.
