### ISSUE TITLE
UI calls column types "string" when they have no native arrow js-api implementation

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/web-client-ui#1597]
**Description**

In the UI, columns whose types should be (for example) `ZoneId` or `LocalDateTime` get called `String` types when hovering over the column names. These columns should be called their correct types, with an additional message that mentions the string preview.

**Steps to reproduce**

Run the following code:
```
from deephaven import empty_table

t = empty_table(10).update(['tz1 = parseTimeZone("GMT")', 'tz2 = parseTimeZone("America/New_York")'])
t = t.update(["ldate1 = '2022-03-28'", 'ldate2 = parseLocalDate("2075-08-08")'])
t = t.update(["ltime1 = '10:15:30.46'", 'ltime2 = parseLocalTime("12:01:01.4567")'])
```

**Expected results**

When I hover my mouse over any of these columns, I expect to see their types displayed as `ZoneId`, `LocalDate`, etc.

**Actual results**

The types get labelled and displayed as strings, but the metadata table confirms that they are actually of the correct type:

<img width="868" alt="Screenshot 2023-10-24 at 10 30 05 AM" src="https://github.com/deephaven/web-client-ui/assets/80283343/bc29d9a1-735e-4683-8fc2-4526e6c3b360">
<img width="866" alt="Screenshot 2023-10-24 at 10 30 17 AM" src="https://github.com/deephaven/web-client-ui/assets/80283343/b005c76d-36c7-4351-b6fe-7646f8129d7a">

**Versions**

 - Engine Version: 0.29.0
 - Java Version: 17
 - OS: MacOS
 - Browser: Safari
 - Docker: NA - built & run with gradle

**Comment by dsmmcken** [comment]
Suggested change: Move the actual column type into the brackets and change the previewing line to "Previewing as String"

**Comment by mofojed** [comment]
Superceded by tickets on the Core side for this: https://github.com/deephaven/deephaven-core/issues/3358
and https://github.com/deephaven/deephaven-core/issues/2102

Web UI doesn't know when a column is converted to a Preview column at the moment.
