### ISSUE TITLE
DateInput - onChange date value should not be optional

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1601]
In `packages/components/src/DateInput.tsx` the `onChange` prop has it's date arg defined as optional. It doesn't appear that this is ever actually the case. We should update it so that consumers don't have to handle the undefined case just to appease TypeScript.

**Comment by sakibian** [comment]
Can I work on this?

**Comment by bmingles** [comment]
@sakibian Yes you may. Here are our contribution guidelines https://github.com/deephaven/web-client-ui/blob/fc543aab57189d5378ae1ebb280fc8024da9ce86/CONTRIBUTING.md
