### ISSUE TITLE
Clicking on a table button in the console should reuse the existing table panel

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1602]
**Description**
Clicking on a table button in the console opens a new panel instead of reusing the existing one.

**Steps to reproduce**

Run this snippet to create a table:
```
e = emptyTable(10).update("x=i")
```

Click on the `e` button a few times. 

**Expected results**
Clicking on the table button should focus on the existing grid panel.

**Actual results**
First click focuses the existing panel, second click opens a new panel with the same table. 

**Versions**
Web UI: 0.51

https://github.com/deephaven/web-client-ui/assets/2853653/bcae9747-8857-4366-a081-acbceff3abba

**Comment by dsmmcken** [comment]
Either fixed, or only exists in enterprise.

**Comment by AkshatJawne** [comment]
Investigated and this no longer is an issue in DHC, closing ticket.

**Comment by mattrunyon** [comment]
DHE ticket where it is an issue https://deephaven.atlassian.net/browse/DH-16614
