### ISSUE TITLE
"View full contents" for text cells should be available from context menu

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#1605]
When a String column is too narrow to display its full contents, there is a button that lets you open a dialog that shows the full contents:

<img width="584" alt="image" src="https://github.com/deephaven/web-client-ui/assets/9516585/31082501-cb8b-458f-9e54-ef382db65236">

This is helpful because the "Cell Contents" dialog lets you select and copy just a portion of the text:

<img width="1164" alt="image" src="https://github.com/deephaven/web-client-ui/assets/9516585/8de504dd-2875-43b9-a0b4-abd5ff5ee4d4">

However, if the column happens to already be wide enough to display the full cell contents, there is no way to get to the "Cell Contents" dialog, since the button disappears:

<img width="764" alt="image" src="https://github.com/deephaven/web-client-ui/assets/9516585/7fe38388-e2f8-44a3-8b3c-415e2a048eb7">

And it is not available in the context menu:

<img width="392" alt="image" src="https://github.com/deephaven/web-client-ui/assets/9516585/1dcad411-7784-47fe-8926-26c130580e7d">

**Comment by vbabich** [comment]
Label as "View Cell Contents". Place as own menu group at the end of list. Only show on string columns.
