### ISSUE TITLE
Values exceeding JS max safe int are formatted incorrectly

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#1638]
**Description**

A `long` type column with a value exceeding JS max safe int (2^53 - 1) can have incorrectly formatted values. It looks like we're using number to pass to the formatter and losing precision

**Steps to reproduce**

Create a table with values over max safe JS int (9007199254740991)

```python
from deephaven.column import long_col
from deephaven import new_table

t = new_table([
    long_col("X", [9007199254740990, 9007199254740991, 9007199254740992, 9007199254740993, 9007199254740994, 9007199254740995])
])
```

**Expected results**

Correct values. Ending in 0, 1, 2, 3, 4, 5

**Actual results**

Some incorrect values. Ending in 0, 1, 2, 2, 4, 6

**Versions**

 - Web UI Version: 0.54.0 (not sure what the earliest version affected is)

**Comment by niloc132** [comment]
See https://github.com/deephaven/deephaven-core/issues/4818#issuecomment-1808774869 - this is probably not a web UI issue, but a dh.NumberFormat bug.

**Comment by mattrunyon** [comment]
Ok I confirmed it's just our typescript types are wrong and not the actual value we pass. We say `format(value: number`, but in reality it's `format(value: number | LongWrapper`. Confirmed the runtime value is a longwrapper. Not a web UI issue, just JS API
