### ISSUE TITLE
Weird space behaviour from monaco

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#165]
Select text in a monaco editor that has indentations. It goes wacky when selected.

https://user-images.githubusercontent.com/1576283/130279720-0c232dba-1ec8-4a68-b2cc-308b2bac4225.mp4

**Versions**
 - Deephaven: Version 0.2.1
 - OS: Win
 - Browser: Chome
 - Docker: ...

**Comment by mofojed** [comment]
![image](https://user-images.githubusercontent.com/4505624/130286631-a74e29ae-b256-4390-a702-bd705cae71b8.png)

**Comment by dsmmcken** [comment]
context?

**Comment by mofojed** [comment]
This happens because the fonts were not preloaded correctly before monaco starts up in the application-mode branch.

**Comment by nbauernfeind** [comment]
Note that the linked bug happens on the main branch, too. Specifically, when you highlight a space it loses its width.

A single space gets the css rule:
```
element.style {
    width: 3px;
}
```

If I kill that style rule in chrome's live CSS editor, then the text looks fine.

**Comment by nbauernfeind** [comment]
Note this also happens with the lines along the left trying to show you the indentation:

<img width="95" alt="Screen Shot 2021-08-24 at 12 01 04 AM" src="https://user-images.githubusercontent.com/1030443/130564350-e44158b0-8025-4581-b915-b7c4bea0423d.png">

**Comment by mofojed** [comment]
There was a race condition between monaco initialization and pre-loading fonts that was more prominent on the (previous) application-mode branch. It occurred when monaco was initialized before all of our fonts are preloaded. By tweaking the AppInit process to require fonts to be loaded before continuing, there's now no more race condition.
