### ISSUE TITLE
Open file blocks logout

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1685]
**Description**

It seems that having an open file stops logout from working.

**Steps to reproduce**

- Run DHC such that it requires PSK for login
- Login
- Open a file
- Try logging out. It should fail
- Close the file
- Try logging out again. It should succeed

**Expected results**

Logout should always work

**Actual results**

Logout only succeeds when no files are open

**Versions**

Engine Version: 0.31.0-SNAPSHOT
Web UI Version: 0.56.0
Java Version: 21.0.1
Barrage Version: 0.6.0

**Comment by mofojed** [comment]
Would be nice to take another look at this. The RefreshTokenBootstrap has been removed.

**Comment by bmingles** [comment]
@mofojed  This still seems to be reproducible on `ghcr.io/deephaven/server-slim:edge`
