### ISSUE TITLE
Add remark-math plugin to MarkdownEditor

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1720]
As a Deephaven user, I want support for math syntax in markdown panels so that I can write math equations.

For example, writing the following in a markdown panel:
```
$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$

$(a+b)^2$

$$\eqalign{
(a+b)^2 &= (a+b)(a+b) \\
&= a^2 + ab + ba + b^2 \\
&= a^2 + 2ab + b^2
}$$
```
Should produce a mathematical output:

$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$

$(a+b)^2$

$$\eqalign{
(a+b)^2 &= (a+b)(a+b) \\
&= a^2 + ab + ba + b^2 \\
&= a^2 + 2ab + b^2
}$$

**Comment by mofojed** [comment]
We need to add the remark-math plugin. Details are at https://github.com/remarkjs/react-markdown#use-remark-and-rehype-plugins-math
Should add this to both MarkdownNotebook and MarkdownEditor (they should be using the same plugins).

**Comment by mattrunyon** [comment]
Katex does not support the `eqalign` environment https://katex.org/docs/support_table.html#e

GitHub uses Mathjax https://github.blog/2022-05-19-math-support-in-markdown/
