### ISSUE TITLE
Change officially supported browserlist to be more restrictive

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1752]
We claim to support browserlist "defaults" as our officially supported browsers (browsers with >0.5% global usage), but that's not actually true. We don't actually support mobile browsers, nor have we ever tested with some of the more obscure browsers. It terms of automated testing, our e2e tests run against chromium, firefox and webkit, so we should treat that as our officially supported list.

We have had this as a question from more than one customer. I propose we narrow our rule to be more specific and not be based on usage but time. In enterprise environments update cadence is generally more on a cycle, like quarterly or every 8 weeks. We should publish a docs page stating what the new rule is that we can refer customers to.

My proposed rule is the last 6 months of any chromium (chrome, edge, opera) or gecko (firefox) based browser, the firefox extended support release (which is every 42 weeks), and the last 1 year of webkit (safari). Safari only does major version bumps annually and the second most used safari version is 7 months old.

```
Chrome > 0 and last 0.5 years,
Edge > 0 and last 0.5 years,
Opera > 0 and last 0.5 years,
Firefox > 0 and last 0.5 years,
Firefox ESR,
Safari > 0 and last 1 year
```

**Comment by mofojed** [comment]
Take a look at how to set the browserslist: https://github.com/browserslist/browserslist?tab=readme-ov-file#best-practices
