### ISSUE TITLE
WidgetPlugin type should be generic

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1759]
Upgrading the plugins repo to the latest DHC release `0.60.0` introduces type errors in some panels when instantiating `PlotlyExpressChartModel`. This can be fixed by making the `WidgetPlugin` type generic for the type of widget it applies to.

**Comment by mattrunyon** [comment]
What type errors are you getting and what are you proposing should be generic? The only thing I could maybe see is `WidgetComponentProps.fetch` returning something you can specify instead of casting it when you fetch

**Comment by bmingles** [comment]
> What type errors are you getting and what are you proposing should be generic? The only thing I could maybe see is `WidgetComponentProps.fetch` returning something you can specify instead of casting it when you fetch

<img width="1223" alt="image" src="https://github.com/deephaven/web-client-ui/assets/1900643/b7f541bf-d65d-41da-a0b6-be89660b9329">

@mofojed and I actually discussed this last week. See the attached PR for what we came up with.
