### ISSUE TITLE
e2e test: Add test to ensure Browser downloads CSV file

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1784]
Right now we have tests to ensure the CSV download operation works: https://github.com/deephaven/web-client-ui/blob/e90b627fed2c76b81ee96006abef14942388f3cc/tests/table.spec.ts#L153
However, it only tests that the Download appears in the UI as succesful. It does not check that the browser actually received the file as a download. We should be able to add a test to ensure the browser received the file as a download: https://playwright.dev/docs/downloads

Note this does seem to be working in Community, but there's a bug in Enterprise where the download is "successful" but then never downloads: https://deephaven.atlassian.net/browse/DH-16455
There will be e2e tests added there, but we should add them on the Community side as well to ensure we don't have a similar bug on community.

**Comment by dsmmcken** [comment]
I would consider further doing a snapshot test on the contents of the CSV itself to make sure those don't change on use either.
