### ISSUE TITLE
Allow re-opening a closed tab panel

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1785]
As a user, I want to be able to re-open a closed panel so that I can restore with it's state if I accidently close a tab.

Suggested changes:
- Remember the last 15 (arbitrary number?) closed panels PER dashboard, their location and their the state when closed. This can be ephemeral between sessions, doesn't need to be persisted.
- Add a configurable shortcut (win: alt+shift+t / mac: opt+shift+t) to re-open the closed tab
- Add a context menu action to the panel tabs, with a right click menu option for "Re-open closed panel". It should appear in it's own group just above the close group, and display the appropriate shortcut.

Re-opening a closed tab should restore state (ie. filters, sorts, linker etc should be resorted) and pop it from the list of closed tabs. We may not be able to re-open in the same place if the stack the tab was part of is removed, so it should instead re-launch in a new position if required (but ideally opens in the same location).

**Comment by mofojed** [comment]
@dsmmcken Context menu on the panel tab? Shouldn't text be "Re-open closed panel" instead? What about if you remove the last panel from the dashboard, what do you right click on then?

**Comment by dsmmcken** [comment]
I suppose we could conditionally show a button on the "Dashboard is Empty" screen (as button centered below that text) if there's panels available to be re-opened. Does that screen exist now in DHC?
