### ISSUE TITLE
Using inline code blocks breaks notebooks and don't work properly on panels

### ISSUE THREAD

**Issue by wusteven815** [deephaven/web-client-ui#1817]
When adding an inline code block like:
```
`a`
```
- In a notebook will break it with the error `TypeError: Cannot read properties of undefined (reading 'inTable')`
- In a panel will create a full code block instead

![image](https://github.com/deephaven/web-client-ui/assets/93849557/2f9b3931-50e3-4715-8790-15bd8d29d18c)

**Comment by mofojed** [comment]
Regression in behaviour, likely caused by https://github.com/deephaven/web-client-ui/pull/1734
