### ISSUE TITLE
InputTable edit state is error on double-click

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1818]
**Description**

> Should the user be able to type in a field when the field is simply highlighted blue?  If so, then why doesn’t the Discard/Commit pop-up immediately show like it does when you doubleclick and the field is red?

**Steps to reproduce**

**Expected results**

**Actual results**

**Additional details and attachments**

**Versions**

 - Engine Version: ...
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by dsmmcken** [comment]
Closing as not reproducible.
