### ISSUE TITLE
Table object not replaced after opened from Panels menu

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#182]
**Description**
If you open a table from the Panels menu, then re-assign that variable to another table, it opens up a new table instead of replacing the existing table. See attached video.

https://user-images.githubusercontent.com/4505624/132010277-6d6417ea-826d-4d73-835c-771736770cfe.mov

**Steps to reproduce**
1. Create a table using a command, eg. `t = emptyTable(100).update("A=i")`
2. Open the table `t` from the panels menu
3. Re-assign the table `t` to another variable, eg. `t = emptyTable(50).update("B=i*2")

**Expected results**
3. Re-assigned table `t` should replace the already open panel for `t`

**Actual results**
3. A new panel is opened for `t`, leaving the old panel open

**Comment by dsmmcken** [comment]
Should it replace? Having multiple views of the same table isn't a bad thing. What's bad is it has a separate base table subscription, and doesn't update when it does. Panel menu was designed for dashboards, so I get this behaviour, but yeah maybe we need to adjust for code studios.

Note this applies to right click, make panel copy as well.

**Comment by mofojed** [comment]
Okay, so you can open the same table multiple times from the Panels menu, but then that table should update when the table object is updated on the backend. That makes sense

**Comment by mofojed** [comment]
Note this is also a problem if "Auto Launch Panel" is unchecked. It will not update the open table automagically.

The table panel itself should be listening if the variable it's created from changes.
