### ISSUE TITLE
DH-16532: Hide the "Expand row and all children" shortcut if the expandAll function isn't available

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1822]
Legacy tree tables don’t have the `JsTreeTable.expandAll` function. TreeTable row tooltip in IrisGrid should show the shortcut to expand the row and all children conditionally, based on feature availability.
<img width="361" alt="Screenshot 2024-02-21 at 12 52 36 PM" src="https://github.com/deephaven/web-client-ui/assets/2853653/daa2c54c-96ac-4890-a978-d4275c7662fe">

**Comment by mofojed** [comment]
Should just not show that text if `!model.isExpandAllAvailable`
