### ISSUE TITLE
Go to value does not work as expected

### ISSUE THREAD

**Issue by rcaudy** [deephaven/web-client-ui#1827]
**Description**

"Go to value" appears to be broken.

**Steps to reproduce**

1. Run my script:
```
from deephaven.table_factory import new_table, empty_table
bad_rows = new_table({"Row": [10, 20, 30, 40, 50, 1000000, 99999999]}).update_view("Bad=true")
raw = empty_table(100000000).update_view("Row=ii")
decorated = raw.natural_join(bad_rows, "Row", "Bad").update_view("Bad=Bad == null ? false : Bad")
formatted = decorated.format_row_where("Bad", "RED")
```
2. Rick click a row in the "Bad" column, and select "Go to".
3. Specify "Go to value" with column "Bad" and value "true".
4. Use the up and down arrows and observe the results.

**Expected results**

I expect that the arrows will move my selection to the next matching row in the direction specified by the arrow, whether or not I have a matching row highlighted.

**Actual results**

Two modes are observed:
1. If I highlight a matching row, clicking either arrow centers that row if not already centered, and then further clicks appear to have no effect.
2. If I highlight a non-matching row, clicking the down arrow brings me to the last matching row in the table, while clicking the up arrow moves me to the next row whether or not it matches.

**Additional details and attachments**

**Versions**

 - Engine Version: ...
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: ...
 - Browser: ...
 - Docker: ...
 
 ```
Version
0.33.0-SNAPSHOT 
```

**Comment by mattrunyon** [comment]
This appears to be an issue with boolean columns at least (could be more column types as well, I didn't check). Using ints works fine

```py
from deephaven.table_factory import new_table, empty_table
bad_rows = new_table({"Row": [10, 20, 30, 40, 50, 1000000, 99999999]}).update_view("Bad=true")
raw = empty_table(100000000).update_view("Row=ii")
decorated = raw.natural_join(bad_rows, "Row", "Bad").update_view("Bad=Bad == null ? 0 : 1")
formatted = decorated.format_row_where("Bad==1", "RED")
```

**Comment by rcaudy** [comment]
I concur that this works with `int`. It does not work with `String`:
```
from deephaven.table_factory import new_table, empty_table
bad_rows = new_table({"Row": [10, 20, 30, 40, 50, 1000000, 99999999]}).update_view("Bad=1")
raw = empty_table(100000000).update_view("Row=ii")
decorated = raw.natural_join(bad_rows, "Row", "Bad").update_view("Bad=isNull(Bad) ? 0 : Bad")
formatted = decorated.update_view("Bad=Integer.toString(Bad)").format_row_where("Bad=`1`", "RED")
```

**Comment by wusteven815** [comment]
@rcaudy

Could be an issue with `SeekRow.java` in core. 

https://github.com/deephaven/deephaven-core/blob/b01510b185d7c167721ca4d3cd1643bd20fcdf07/ClientSupport/src/main/java/io/deephaven/clientsupport/gotorow/SeekRow.java#L47-L60

```java
    public Long apply(Table table) {
        final int sortDirection = guessSorted(table);
        final boolean isSorted = !contains && sortDirection != 0;

        final RowSet index = table.getRowSet();
        long row;
        if (isSorted) {
            final Comparable value =
                    (Comparable) table.getColumnSource(columnName).get((int) index.get((int) startingRow));
            final int compareTo =
                    sortDirection * nullSafeCompare(value, (Comparable) seekValue) * (isBackward ? -1 : 1);
            final int start = isBackward ? (int) startingRow + 1 : (int) startingRow;
            if (compareTo == 0) {
                return startingRow;
```

For string (and booleans), `isSorted == true` and `compareTo == 0`, so it returns the starting row, which is why the selection doesn't change. For ints, `isSorted == false`, so it runs a find algorithm below, which moves the selection.

**Comment by rcaudy** [comment]
It's noteworthy that the table service integration for `SeekRow` is apparently relying on a spurious `@ConcurrentMethod` annotation here and not using any locks. This adds extra-raciness to the results.

**Comment by wusteven815** [comment]
Fixed by https://github.com/deephaven/deephaven-core/pull/5238
