### ISSUE TITLE
deephaven.ui widgets do not appear in Console dropdowns

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1884]
**Description**

When you create deephaven.ui components, they do not appear under the Console table or widget dropdowns. They're only under the Panels menu.

**Steps to reproduce**

1. Create a deephaven.ui widget in the console:
```
from deephaven import ui

foo = ui.text("Bar")
```
2. Check the table/figure dropdowns in the Console panel

**Expected results**
2. `foo` should appear in a dropdown and be openable

**Actual results**
2. `foo` does not appear in either dropdown. It only appears under "Panels"

**Additional details and attachments**
We should consider having one dropdown for all the objects, with a filter in that dropdown for type? The dropdown is redundant of the Panels menu, get rid of it entirely (for Core)?

**Versions**
Engine Version: 0.34.0-SNAPSHOT
Web UI Version: 0.69.1
Java Version: 11.0.22
Barrage Version: 0.6.0
Browser Name: Chrome 122
OS Name: Linux

**Comment by dsmmcken** [comment]
> get rid of it entirely (for Core)

> consider having one dropdown for all the objects (for enterprise)

I support that.

**Comment by mofojed** [comment]
@wusteven815 you should be able to just delete `ConsoleMenu`, and just pull the "More Actions..." part up into `ConsoleStatusBar`.

For Enterprise I'll take care of consolidating the dropdown when I convert to use the Core Console Plugin from Enterprise (DH-16756)

**Comment by mattrunyon** [comment]
The console dropdown and panels menu have a slight behavior difference in enterprise at least.

Console dropdown -> reopen over existing panel the console opened (DH-16614 is a bug w/ this behavior)
Panels menu -> open new panel w/ the widget

From the panels menu you can open the same widget multiple times. I think it's fine to combine as the difference is not communicated to users, but just wanted to note it

**Comment by mofojed** [comment]
Related to #1962
