### ISSUE TITLE
Update ValidateLabelInput to match the Enterprise version of the component

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1885]
`ValidateLabelInput` in Enterprise has additional props that are missing in the Community version of the component:
- `labelClassName`
- `tooltipText`
- `isRequired`

Functionality changes:
- pass the `isInvalid` prop to the child component
- pass the `id` prop to the child component

**Comment by dsmmcken** [comment]
Is this used at all in  community? 

Possibly belongs as only enterprise.

**Comment by vbabich** [comment]
Used only on the styleguide page. Should I delete it in Community then?

**Comment by dsmmcken** [comment]
Since this is only used in enterprise query monitor and enterprise parameterized querys we should just delete it from web-client-ui and maintain it only in enterprise.
