### ISSUE TITLE
Log and console break if process is not defined

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#189]
**Description**

Log and console rely on process.env. This makes the components (and any which rely on log) not usable without polyfilling process.env in environments without the value set.

We have this value replaced by webpack in CRA. This is a webpack 4 specific feature it seems and is not provided by default in webpack 5. https://stackoverflow.com/questions/64475910/replacing-polyfill-for-process-in-webpack-v5-from-v4

We should gracefully fallback to defaults instead of crashing if process is not defined

**Steps to reproduce**
1. Use a component which requires log or console in a browser-based project without webpack 4 (docs is an example).

**Expected results**
No errors

**Actual results**
Errors because process is not defined

**Additional details and attachments**
Current workaround (for browsers) is to use the following
```
window.process = {
  env: {},
};
```

**Versions**
 - Deephaven: 0.3.1

**Comment by mofojed** [comment]
@mattrunyon is this blocking you?

**Comment by mattrunyon** [comment]
No I have a workaround and am not using packages which rely on log
