### ISSUE TITLE
DH-16865: Partitioned table with no data displays a spinner indefinitely

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#1904]
Steps to reprodude:

Run this snippet to create a partitioned table with no data:
```
from deephaven import empty_table
t = empty_table(0).update("X=ii").partition_by("X")
```
Expected:
- Table loads with no data rows

Actual:
- Table shows a spinner, doesn't load

**Comment by mattrunyon** [comment]
Test it works if the table is ticking and a partition is added at least. This will load for around 20s until the first row ticks in

```py
from deephaven import time_table
t2 = time_table("PT20S").update("X=ii").where("X>0").partition_by("X")
```

**Comment by vbabich** [comment]
> // We want to wait for the first UPDATED event instead of just getting viewport data here
> // It's possible that the key table does not have any rows of data yet, so just wait until it does have one

https://github.com/deephaven/web-client-ui/blob/main/packages/iris-grid/src/IrisGrid.tsx#L2042

**Comment by mofojed** [comment]
We can show the empty table until the first key ticks in, in which case then we want to select that first key.

**Comment by illumon-public-sunil** [comment]
This is an issue in both Core+ and Legacy workers and is present in 1.20231218.219 as well.

Attaching images of Core+, Legacy worker and swing

![image](https://github.com/deephaven/web-client-ui/assets/119700885/294ca22b-647e-49a8-883e-8017fb3c9e89)

![image](https://github.com/deephaven/web-client-ui/assets/119700885/85bd7d53-4ba1-49b8-84f9-558ab5f5280b)

![image](https://github.com/deephaven/web-client-ui/assets/119700885/5db4e8b8-30d3-46f6-878f-a97533f5c72b)

**Comment by illumon-public-sunil** [comment]
Noticed the same behavior on a query that includes a where clause. However, the filter column used in where clause is not the partition column, behavior is the same in Legacy and Core+.

Adding empty where() to the end of the query works.

Adding the comment just to capture another use case.

**Comment by AkshatJawne** [comment]
Verified that my changes do not fix this issue, can still see the spinner. Attempted to tested changes proposed in #1953 , but running into a lot of errors (I would assume that surrounding code has changed quite a bit in the interim). Looking at how we can combine both solutions here.
