### ISSUE TITLE
Click in an expanded exception in the Console should not collapse it

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#192]
**Description**

If I click anywhere in an expanded exception, it minimizes the exception.
I feel like it should only expand/collapse if you click the caret on the left.

**Steps to reproduce**
1. Type any command resulting in an exception in the console, i.e. `test`
2. Click on the red collapsed exception text to expand it
3. Click anywhere in the expanded exception text

**Expected results**

The exception stays expanded.

**Actual results**

The exception gets collapsed.

**Comment by mofojed** [comment]
@spasovski work on closing out this ticket. Discuss exact change with @dsmmcken

**Comment by mofojed** [comment]
Also we should make sure that right-click doesn't cause the exception to collapse either.

**Comment by dsmmcken** [comment]
I would make it so the whole line still acts as the toggle, not just the triangle. Also make sure the cursor and hover state is properly reflected for that line, and not the unfurled content.
