### ISSUE TITLE
Playwright CI tests can be sharded to run faster

### ISSUE THREAD

**Issue by wusteven815** [deephaven/web-client-ui#1933]
See https://playwright.dev/docs/test-sharding

**Comment by mofojed** [comment]
Timebox to a day for research, then re-evaluate.

**Comment by mattrunyon** [comment]
Could try doing a build, uploading the build as an artifact (+ node_modules maybe), then using a matrix task based on browser. Each of those tasks just downloads the build artifact to start so we don't duplicate the build
