### ISSUE TITLE
iris grid partition selector can only display 1000 partitions

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1970]
```
from deephaven import empty_table
t = empty_table(15000).update(["x = i", "y = i"]).partition_by(["x"])
```

Viewing multiple years of a daily partitioned table can easily exceed the 1000 item limit. The partition select is limited by us to 1000 items for performance. (And is capped by the browser at 10000 in chrome).

We should switch the selector to use the spectrum select which is virtualized and can handle a much higher number of rows (hundreds of thousands).

**Comment by mofojed** [comment]
Should use the `Picker` component from `@deephaven/jsapi-components`.
