### ISSUE TITLE
ListView - wire up change handlers

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#1985]
ListView onChange and onSelection change are being passed into ListView but not consumed resulting in them not working

**Comment by mofojed** [comment]
@bmingles It's not just onChange, other props aren't wired up as well, such as `UNSAFE_className`: https://github.com/deephaven/web-client-ui/blob/a283e13fafe1ecb156985fab00ba15344f180ff4/packages/components/src/spectrum/listView/ListView.tsx#L55
