### ISSUE TITLE
More friendly error format when UI 'gives up'

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/web-client-ui#201]
This is somewhat related to #181. However, it differs in that this feature request is a request to enhance the existing bandaid.

After merging deephaven/deephaven-core#1210, if the `grpc_api` server process exits cleanly as a response to an internal error, it now will share that error with the user. It might be nice if this error message is not text-aligned to center, and is dropped into a scrollable box.

It might be useful to leave a link to any FAQ for out-of-memory and common user errors/mistakes. It might be useful to leave a link to the `web-client-ui/issues` tab and to the `deephaven-core/issues` tab.

<img width="1502" alt="Screen Shot 2021-09-17 at 11 11 42 AM" src="https://user-images.githubusercontent.com/1030443/133827676-3e6abacf-f1a0-4623-ae5d-5eaded5f6478.png">

**Comment by mofojed** [comment]
@nbauernfeind Can you detail easy steps to reproduce? Is the error message propagated from the API a String or an error object with more details?
