### ISSUE TITLE
UI should differentiate between Partitioned Tables and Partition-Aware Source Tables

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#2049]
If I have a PartitionAwareSourceTable, I get the partitioned table viewer in the UI, which is very helpful, but a bit confusing because it tells me I have a "Partitioned Table":

![image](https://github.com/deephaven/web-client-ui/assets/9516585/1423a645-4d95-48c6-8e39-802dd3bed8c0)

It _is_ a partitioned table in the sense that "it is a table, and it has partitions", but it's not an actual `io.deephaven.engine.table.PartitionedTable`.

It would be helpful if there were some way to see in the UI what the actual table type is (like some small text under "where it says "Partitioned Table" with the class name...or even a tooltip when you hover over "Partitioned Table", or the table's tab).

**Comment by vbabich** [comment]
@rbasralian Why is it important to know the distinction in the UI? I don't think the UI can get this information at this point.

**Comment by rbasralian** [comment]
It's not a huge deal but it's confusing. The words "partitioned table" mean something different & [pretty specific](https://deephaven.io/core/javadoc/io/deephaven/engine/table/PartitionedTable.html) when you're writing a query. In this case I had a regular table not a PartitionedTable, and [I got hung up for a few minutes](https://illumon.slack.com/archives/G01K6UHJ00K/p1717190877206539) trying to understand what table operations like `.where()` would actually return and whether I'd have to call [`.merge()`](https://deephaven.io/core/javadoc/io/deephaven/engine/table/PartitionedTable.html#merge()) at some point in the query.

The "Merge" button in the UI makes it even more confusing, because with a [PartitionAwareSourceTable](https://deephaven.io/core/javadoc/io/deephaven/engine/table/impl/PartitionAwareSourceTable.html) like this, you generally don't think of "view all partitions" as a "merge" operation — since it's not actually a `merge()` but rather a `.where()` with no arguments.

**Comment by vbabich** [comment]
I think our partitioning UI and underlying data models intentionally make both kinds of tables behave as if they were the same. This is probably fine for basic use cases but might be confusing when the table type is important. I also had this issue once and had to call `.getClass()` on a table object to get this information.

**Comment by vbabich** [comment]
@rbasralian We could re-label `Partitioned table` as `Partition-aware source table` and change the `Merge` button to something more appropriate. Would the label `Coalesce` make more sense for partition-aware source tables? Or something else?

**Comment by dsmmcken** [comment]
See #2079 for details
