### ISSUE TITLE
EPIC: Partitioned Table UI improvements

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#2079]
Summarizing changes to be made:

- [x] Fix table dying under the agg condition (#2066)

New changes For Partitioned Tables:
- [ ] #2103
- [ ] #2104
- [ ] #2105
- [ ] #2106
- [ ] #2107

New changes for Partitioned Aware Source Table
- [ ] #2108
- [ ] Re-label merge as "Coalesce"  (#2049)
- [ ] #2109

**Comment by AkshatJawne** [comment]
Close to completing all enhancements outlined in epic, currently working through adding double click functionality through a mouse handler.

**Comment by AkshatJawne** [comment]
Someone with permissions, need to reopen ticket, only have merged in Java side changes, UI changes still in review / adding functionality for empty table

**Comment by AkshatJawne** [comment]
Only have merged in Java side changes, UI changes still in review / adding functionality for empty table bug
