### ISSUE TITLE
Modify Picker logic responsible for updating options from table

### ISSUE THREAD

**Issue by AkshatJawne** [deephaven/web-client-ui#2120]
In order to remove manual setting of viewport after applying filter proposed here: https://github.com/deephaven/web-client-ui/pull/2096

**Comment by bmingles** [comment]
@AkshatJawne I think this is the spot where additional filter factories can be applied:
https://github.com/deephaven/web-client-ui/pull/2077/files/c0407f68039b9a8e9019756fae0dccdd843a08be#diff-9542f417ebf6c532d214f67543fd42775b65557024e6dee5b4a8d3b8107dbccbR75

Will need to wait on https://github.com/deephaven/web-client-ui/pull/2077 to merge.

**Comment by AkshatJawne** [comment]
No longer adding filter prop, but refactored the way partition options are updated in the picker in #2110
