### ISSUE TITLE
Floating Cell when editing in Iris Grid

### ISSUE THREAD

**Issue by AkshatJawne** [deephaven/web-client-ui#2153]
Similar to applications like Google Sheets, I would propose the addition of a floating or sticky cell editing feature. This feature would allow the cell being edited to remain visible and accessible to the user, even as they scroll through the grid.

**Important Notes:**
- Unlike Google Sheets, we would want to display the cell coordinates next to the floating input (may have to modify styling since it could get cluttered with a long column names)
- We do not want to display the row headers by default

**Reference Image:**
![image](https://github.com/user-attachments/assets/2e39aef4-0bea-4557-8e85-c51937989b47)

**Comment by vbabich** [comment]
We don't have row indexes, so it doesn't make sense to float since users wouldn't know what row it is.
