### ISSUE TITLE
Flashing float column

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/web-client-ui#2165]
I noticed a situation on a server-sorted table where the text colors on a float column of near zero values was flashing as I moved my mouse over the float column; the viewport was not being scrolled. I added a custom column via UI, `XStr = Float.toString(X)` to see more detail on the floating point values. It looks like the difference between the yellow text and the green text is due to a small positive value (ie, green text represents a positive value) - so that explains why the text is a different color, but it doesn't explain why the color was flashing from between the colors. With the addition of the custom column, notice that that custom column also disappears during the flashing behavior. I didn't screen record my mouse movements, but it consistent of moving up and down across the range of X values; stopping the mouse movement stopped the flashing behavior.

https://github.com/user-attachments/assets/0a0381a6-04bb-4c7c-8955-84ba52efe94f

After recording the video, I tried to reproduce the behavior, but was unable to - this video is the only evidence I have.

Here is the server side code, where I was specifically testing out large server-side sorts (takes about 90s to run, although hopefully any reproducer would be able to use much smaller size; TBD).

```groovy
import io.deephaven.engine.util.TableTools
import java.util.Random

random = new Random(31337L)

x = TableTools.emptyTable(1L << 29).select("X=random.nextFloat()")

xSorted = x.sort("X")
```

Engine Version: 0.36.0-SNAPSHOT
Web UI Version: 0.86.1
Java Version: 22.0.2
Barrage Version: 0.6.0
Browser Name: Firefox 128
OS Name: Linux

**Comment by devinrsmith** [comment]
Here's another very similar issue. Any slight mouse movement caused this big flashing behavior.

https://github.com/user-attachments/assets/d39421c0-6081-42d0-846c-c4d9427ce89c

**Comment by devinrsmith** [comment]
Note: I was able to reproduce this without a proxy as well (just trying to eliminate variables).

**Comment by vbabich** [comment]
@devinrsmith is there a reproducer for the second issue?

**Comment by devinrsmith** [comment]
The triggering conditions were very similar to https://github.com/deephaven/web-client-ui/issues/2139; ie, a lot of random fast clicks in the UI. In this case though, the proxy was removed. It's possible it's the same underlying issue, just manifesting a bit differently when in the presence or not of a proxy. I suspect some sort of race somewhere causing some sort of issue.

**Comment by vbabich** [comment]
@AkshatJawne can you see if you can reproduce this?

**Comment by AkshatJawne** [comment]
Tried reproducing, I could not reproduce @vbabich

**Comment by devinrsmith** [comment]
Here's a similar looking flashing column; the table is a lastBy table (always 1 row) that was originally ticking, but now the data source has stopped so it should be unchanging.

As I move the mouse around, it seems to flash to previous versions of the table...

https://github.com/user-attachments/assets/428c8306-00d1-4dc6-89fd-7dd5aa0ba9a1

I'm not reliably able to reproduce.

**Comment by mofojed** [comment]
Akshat looked into this and was unable to reproduce...
@devinrsmith if you can give a python snippet reproducing this reliably please reopen.
