### ISSUE TITLE
Cannot copy with syntax highlight from Notebook

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#218]
**Description**

When you copy code from a notebook, it only copies as plaintext, it does not copy without formatting.

**Steps to reproduce**
1. Open a notebook
2. Select a snippet in the notebook, copy (Ctrl+C)
3. Go to a rich text field (ie. Google Slides), and paste (Ctrl+V)

**Expected results**
3) Snippet is pasted with syntax highlighting/formatting

**Actual results**
3) Snippet is copied without formatting

A clear and concise description of what actually happened.

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: v0.4.0

**Comment by mofojed** [comment]
This is because we added the `copyWithSyntaxHighlight: false` flag, in an old Merge Request: https://gitlab.eng.illumon.com/illumon/iris/merge_requests/3712
We thought copying with formatting would be annoying; in our case, it may be since we use a dark theme, which gives the text a dark background when pasting. However, we should probably still leave the flag set to `true` and formatting can be removed when pasting so the user has the option.

**Comment by mofojed** [comment]
Rinsing through an IDE isn't necessarily the best option either, since an IDE would not have the same syntax highlighting as we do (we format strings for Java formulas in our Groovy syntax highlight, for example):
![image](https://user-images.githubusercontent.com/4505624/135914165-8c9abea8-ae1b-495b-9e9a-cac1c1cf4270.png)

**Comment by dsmmcken** [comment]
Disagree, I still think it's better to just copy the plaintext for all most all user needs.

The super-rare use case of needing formatting for a presentation or otherwise, doesn't make sense as to make it the default.

**Comment by dsmmcken** [comment]
#170 I would be fine with exposing it as an option if we ever get around to that though.
