### ISSUE TITLE
Include Python/Groovy version info in the Web UI

### ISSUE THREAD

**Issue by jmao-denver** [deephaven/web-client-ui#2184]
As a user, I want to quickly find out what Python/Goovy version my console is running in so that it makes it easier for me to debug potential problems caused by incompatibility between versions.

**Comment by mattrunyon** [comment]
@devinrsmith I think this will need a bit of server work to expose the Python/Groovy version to the client

**Comment by devinrsmith** [comment]
I think the groovy bit would be relatively easy, given our current method that looks at jar versions. Python will take a bit of a different approach I suspect, but shouldn't be too much of a lift.

**Comment by devinrsmith** [comment]
The server side is now publishing `groovy.version` (and `python.version` when there is a python script session). Note that `groovy.version` *is* still published when running a python script session since it's still technically on the classpath.
