### ISSUE TITLE
@deephaven/utils - errors when installing in vscode extension

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#2185]
I attempted to install @deephaven/utils in the vscode-deephaven extension and get a number of errors:
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/2505187c-cde8-4dc3-b318-1003eb7fa44b">

It looks like there are at least 2 classes of errors here:
- Incompatible `CustomEvent` type (presumably due to differences in TypeScript version or tsconfig target)
- References to `jest`. This dependency is not declared in `package.json`. We may also want to remove the dependency on `jest` from `@deephaven/utils` altogether since not all consumers would be using `jest` as their testing framework.

**Comment by mofojed** [comment]
> References to `jest`

We should move test code such as `TestUtils` into it's own directory, and possibly it's own package `@deephaven/test-utils` to lump a bunch of test utilities together.

**Comment by bmingles** [comment]
> > References to `jest`
> 
> We should move test code such as `TestUtils` into it's own directory, and possibly it's own package `@deephaven/test-utils` to lump a bunch of test utilities together.

My vote would be a separate package since it's not guaranteed that consumers will use jest at all.

**Comment by mofojed** [comment]
To clarify my previous comment... files that depend on `jest` or `@testing-library/*` or any of our other testing libraries/`devDependencies`, should _not_ be included in the package build output and should be removed. It may make sense to move them all to a `@deephaven/test-utils` package (especially [TestUtils](https://github.com/deephaven/web-client-ui/blob/main/packages/utils/src/TestUtils.ts), which is used by many of our other packages for testing), or simply moved to a folder that is excluded from build output (such as `ChartTestUtils`, which is not needed in any other package).
