### ISSUE TITLE
Increase minimum space between Tooltip Title and Table Name in Stats Summary Pop Up

### ISSUE THREAD

**Issue by nbauernfeind** [deephaven/web-client-ui#2254]
When hovering over a tab name on a Hierarchical Table, the name of the tab squishes up against the tooltip title.

```groovy
import io.deephaven.util.QueryConstants
import io.deephaven.engine.table.impl.util.PerformanceQueries
import  io.deephaven.engine.table.impl.util.TableLoggers

qpl = TableLoggers.queryPerformanceLog()
qopl = TableLoggers.queryOperationPerformanceLog()
qpl_tt = PerformanceQueries.queryPerformanceAsTreeTable()
qopl_tt = PerformanceQueries.queryOperationPerformanceAsTreeTable()
```

![Screenshot 2024-10-14 at 10 25 56 AM](https://github.com/user-attachments/assets/1f2bc7ba-ae70-4517-9196-f0e77afda10f)

I would expect a small amount of space to be reserved between the two to improve readability.

Note that Table widgets don't seem to have this issue:
<img width="319" alt="Screenshot 2024-10-14 at 10 49 04 AM" src="https://github.com/user-attachments/assets/297da1d4-00b5-4031-b52e-9054348e718c">

**Comment by vbabich** [comment]
Looks like there's no spa
<img width="425" alt="Screenshot 2024-10-14 at 10 52 30 AM" src="https://github.com/user-attachments/assets/221ed454-717a-46bd-bf5d-96897fa49141">
cing in the grid:
