### ISSUE TITLE
OS version listed by the IDE is incorrect

### ISSUE THREAD

**Issue by chipkent** [deephaven/web-client-ui#2289]
My mac is `14.2.1`.  In the IDE, the version is reported as `10.15.7`.  The problem exists in both normal and incognito modes.  It also exists on Chrome and Safari.

**Comment by mofojed** [comment]
Reproducible on my Mac which is on 15.1. Seems to a known issue across browsers: https://bugs.webkit.org/show_bug.cgi?id=216593

**Comment by mattrunyon** [comment]
@mofojed What is your user agent string? We just parse that using a library, so would be good to check if it's an issue with the UA or with the parser we use (`bowser` which hasn't been updated in 4 years)

**Comment by mattrunyon** [comment]
We should probably just drop OS version. It's not accurate and there are more pushes towards removing or setting a fixed version. See [this page](https://developers.google.com/privacy-sandbox/protections/user-agent) for an example w/ Android/chrome fixing some versions.

[userAgentData](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData) might be the best replacement, but it's currently a chromium only implementation

**Comment by dsmmcken** [comment]
Renaming "OS Name" to  "User Agent OS", as that is still the true value reported by the browser. Don't want to drop it as more info is better than less.

Bowser is probably one of those packages that is "complete", it is splitting out the UA correctly. That's just what the os is reporting
