### ISSUE TITLE
Web UI should allow using doubles as rollup key columns

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#2295]
A user found that they can't use double columns as key columns in rollups they create in the web UI. Although there are many cases where doubles don't make sense as key columns (e.g. truly continuous values such as prices or calculation outputs), there are also plenty of cases where there is a distinct set of values that does make sense as key columns (e.g. 1.0, 2.0, 3.0, etc.)

**Comment by mofojed** [comment]
We filter out decimal types by default: https://github.com/deephaven/web-client-ui/blob/5ebc19574f20ade69a179cd5615c6547aa0a9b90/packages/iris-grid/src/sidebar/RollupRows.tsx#L117
We could just not do that and it should work.
