### ISSUE TITLE
ComboBox should show full list on initial open

### ISSUE THREAD

**Issue by bmingles** [deephaven/web-client-ui#2300]
When using table data sources, `ui.combo_box` currently only shows filtered items on open if there is a selection. This is different than how React Spectrum ComboBox typically works as well as `ui.combo_box` configurations that use static item data sources. This has been reported in the plugins repo [ComboBox table source behavior inconsistent #1024](https://github.com/deephaven/deephaven-plugins/issues/1024), but it will likely need to be addressed in the hooks that handle windowed data that live in web-client-ui.

**Comment by mofojed** [comment]
Migrated to: https://deephaven.atlassian.net/browse/DH-18088
