### ISSUE TITLE
dragging column separator to decrease column size formatting issue

### ISSUE THREAD

**Issue by spasovski** [deephaven/web-client-ui#267]
Consistently reproducible with two adjacent numeric columns. There is a breakpoint at which the value gets `text-overflow: ellipsis` and the values overflow into each other. Seems to be an issue everywhere but is more apparent with frozen columns.

<img width="155" alt="image" src="https://user-images.githubusercontent.com/391260/139495048-85e7a1c4-fbb6-479a-9c76-f369e608e6b8.png">

**Comment by dsmmcken** [comment]
fixed by #278
