### ISSUE TITLE
Create `allRowHeights` and `allRowYs` maps

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#316]
Right now there are `visibleRows` and `allRows`, where `visibleRows` is just the visible rows in the main viewport, and `allRows` is all the rows including floating rows. However, there is just one map `visibleRowHeights` that has all of the heights (including floating rows). This is pretty confusing, and we should split it out.

**Comment by dsmmcken** [comment]
There's also an issue with including hidden columns in this list, causing funny business with scrolling. Not sure if that can also be addressed.
