### ISSUE TITLE
Scrollbars appear when File Explorer tab is active

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#349]
**Description**

Scroll bars appear when you have the File Explorer tab active. See screenshot.

**Steps to reproduce**
1. Activate File Explorer

**Expected results**
1. No scrollbars on the viewport

**Actual results**
1. Scroll bars on the viewport

**Additional details and attachments**
![image](https://user-images.githubusercontent.com/4505624/145641390-4db98711-fb27-4e86-974a-1b299bf557e7.png)

**Comment by mattrunyon** [comment]
Only seems to occur if file explorer is almost the full page height
