### ISSUE TITLE
Update TypeScript version

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#352]
Update TypeScript to v4.5. Also enforce VS Code to use the workspace version of TypeScript, so we don't get discrepancies between workspace and tests.

**Comment by mattrunyon** [comment]
Related to #277 

Object index signatures accessed via array notation must be checked for undefined as of TS 4.4

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures
