### ISSUE TITLE
Enable curly rule in eslint

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#353]
Our preset does not appear to include errors for the "curly" rule in eslint.

https://eslint.org/docs/rules/curly

Enable this rule (probably only the "multi" option is fine) so we don't accidentally end up with invalid code due to missing curly braces after a conditional clause

**Comment by mofojed** [comment]
Yes let's use the `multi` option.

**Comment by mofojed** [comment]
We're actually closer to the `all` rule type than `multi`, since we already wrap most if statements with curlys. I'd prefer to keep that rather than shorten it to one line if it's just one statement (which is what the `multi` rule enforces).
