### ISSUE TITLE
Maintain temporary edits to console history items until execution

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#374]
As a user, I want to be able to edit a previous command (accessed via up arrow on the command line), and not lose my work if I up or down arrow too far while editing a multiline command.

I want to be able start a new command, check a previous command, and return to editing the last command without losing my work.

Changes to behaviour:
- maintain a temporary queue of edits, where edits to previous commands are preserved until a new command is executed
- allow up/down arrow when on the last command and it has been edited, maintain that last command in a temporary queue until a command is executed
- temporary edit queue is cleared when any command is executed (this differs from bash/python command line where it is preserved for ever)

**Comment by mofojed** [comment]
Note that this temporary queue should also apply for a new command entered, eg.
1) Start typing a new command from blank
2) Press up
3) Press down. The command you started typing should still be there
