### ISSUE TITLE
Improve clipboard write handling

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#376]
In `ContextActionUtils.copyToClipboard()` we currently check for the `clipboard-write` permission. This isn't on the w3c spec any more and in Firefox results in a rejected promise. When that happens we fall back to the old/deprecated style of writing to the clipboard.

According to MDN, the `clipboard-write` permission is given to any active tab [link](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText)

MDN is somewhat inconsistent b/c the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions) is not finalized yet.

We should just try writing to the clipboard async and then on rejected promise assume we don't have the permission and fallback to the old method. `writeText` exists in all browsers but IE for over a year now.

**Comment by mofojed** [comment]
Could we abstract this into a hook?
