### ISSUE TITLE
Upgrade to Node 16/NPM 8

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#381]
Node 16 and NPM 8 are the current LTS as of October 2021.

The upgrade to Node 16 should be fairly straightforward I think. Upgrading to NPM 8 allows us to use the NPM workspaces which I think we can leverage instead of `lerna boostrap`. This should drastically improve package install performance as NPM 8 seems to be much better at the dedupe step when everything is already installed. Lerna's bootstrap on the other hand is very slow when you just want to add a new package or install on checkout to verify you are up to date.

**Comment by dsmmcken** [comment]
Note: Node 16 is required for arm based macbooks, and we are starting to have a few of those at Deephaven now, so we'll need to do this to support them as well.
