### ISSUE TITLE
Fix sass deprecation warnings

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#41]
Getting a bunch of deprecation warnings from sass. Fix the division used:
```
@deephaven/code-studio: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
@deephaven/code-studio: Recommendation: math.div($rfs-breakpoint, $rfs-breakpoint * 0 + 1)
@deephaven/code-studio: More info and automated migrator: https://sass-lang.com/d/slash-div
@deephaven/code-studio:    ╷
@deephaven/code-studio: 57 │   $rfs-breakpoint: $rfs-breakpoint / ($rfs-breakpoint * 0 + 1);
@deephaven/code-studio:    │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@deephaven/code-studio:    ╵
@deephaven/code-studio:     ../../node_modules/bootstrap/scss/vendor/_rfs.scss 57:20  @import
@deephaven/code-studio:     ../../node_modules/bootstrap/scss/_mixins.scss 6:9        @import
@deephaven/code-studio:     ../components/scss/custom.scss 230:9                      @import
@deephaven/code-studio:     src/layout/GoldenLayout.module.scss 1:9                   root stylesheet
```

**Comment by mofojed** [comment]
Bootstrap already has an issue for this, as they need to update their code: https://github.com/twbs/bootstrap/issues/34051

We can either add the `--quiet-deps` flag or downgrade to 1.32 in the meantime...

**Comment by mofojed** [comment]
There's no option to pass the `--quiet-deps` flag through `react-scripts`. Just downgrade to 1.32, keep an eye on when can pass quiet-deps through react-scripts (https://create-react-app.dev/docs/adding-a-sass-stylesheet/), or Bootstrap updating their core: https://github.com/twbs/bootstrap/issues/34051

**Comment by dsmmcken** [comment]
Our bootstrap version is pinned, we probably won't get whatever version they put the fix into.
