### ISSUE TITLE
Grid column tooltips don't work when mouse enters from above

### ISSUE THREAD

**Issue by niloc132** [deephaven/web-client-ui#412]
**Description**

**Steps to reproduce**
1. Open a table in the web UI
2. Ensure the new grid panel is in a tab with some content above it - the console, command history, etc
3. From above, bring the mouse over a table column and pause to wait for the tooltip showing column information

**Expected results**
Tooltip shows up within a second or so.

**Actual results**
Nothing happens. User must instead hover first over the table (contents, another column, empty column space, etc).

**Comment by dsmmcken** [comment]
It seems to be limited to the case of enter from above, exit upward, then enter from above again.

showColumnTooltip is never removed from state, so it can never be re-shown, bug introduced by the fix for #306.
