### ISSUE TITLE
Clicking a tab should focus its table

### ISSUE THREAD

**Issue by niloc132** [deephaven/web-client-ui#416]
As a user of tables in the UI, I want clicking a table tab to focus the table, so that keyboard shortcuts work. For example, when I have a value to search in a table, I click the table and type `ctrl-f` to search - this instead brings up the browser "find in page". So, I have to click on the table somewhere to first focus it, and then start searching.

**Comment by dsmmcken** [comment]
related: we have an `onTabFocus` event for panels, but it doesn't look to ever be triggered. todo investigate and remove?
