### ISSUE TITLE
Cannot npm install packages from an npm8 project

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#488]
**Description**

Trying to use npm 8 to install @deephaven/* package dependencies is failing with an error.

**Steps to reproduce**
1. Clone the deephaven-js-plugins repo and check out the `npm-workspaces` branch: https://github.com/mofojed/deephaven-js-plugins/tree/npm-workspaces
2. Run `npm install` (should be using npm 8 because of the .nvmrc)

**Expected results**
2. Install completes successfully

**Actual results**
2. Install fails with an error
```
➜  deephaven-js-plugins git:(npm-workspaces) ✗ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @deephaven/js-plugin-dashboard-object-viewer@0.1.4
npm ERR! Found: @deephaven/log@0.11.2
npm ERR! node_modules/@deephaven/log
npm ERR!   dev @deephaven/log@"0.11.2" from @deephaven/js-plugin-dashboard-object-viewer@0.1.4
npm ERR!   dashboard-object-viewer
npm ERR!     @deephaven/js-plugin-dashboard-object-viewer@0.1.4
npm ERR!     node_modules/@deephaven/js-plugin-dashboard-object-viewer
npm ERR!       workspace dashboard-object-viewer from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @deephaven/log@"^0.3.1" from @deephaven/components@0.11.2
npm ERR! node_modules/@deephaven/components
npm ERR!   dev @deephaven/components@"0.11.2" from @deephaven/js-plugin-dashboard-object-viewer@0.1.4
npm ERR!   dashboard-object-viewer
npm ERR!     @deephaven/js-plugin-dashboard-object-viewer@0.1.4
npm ERR!     node_modules/@deephaven/js-plugin-dashboard-object-viewer
npm ERR!       workspace dashboard-object-viewer from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bender/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bender/.npm/_logs/2022-03-15T23_12_15_445Z-debug-0.log
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by mattrunyon** [comment]
We might want to specify our peer deps w/ `>0.3.x' or something b/c npm treats caret as patch changes only for versions < 1.0.0

So `^0.3.1` is really `>=0.3.1 <0.4` but `^1.3.1` is `>=1.3.1 < 2`

**Comment by mofojed** [comment]
Should be fixed now, js-plugins PR: https://github.com/deephaven/deephaven-js-plugins/pull/1

**Comment by mofojed** [comment]
Also have a ticket to clean up dependencies: #528
