### ISSUE TITLE
Update to react-script 5.0.0 or Vite

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#494]
Update to react-scripts 5.0.0

Follow the migration guide: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md#migrating-from-40x-to-500

**Comment by mofojed** [comment]
It may be handy to do #528 before this ticket as well.

**Comment by mofojed** [comment]
Getting a bunch of issues after updating to react-scripts 5.0.1, which are described here: https://github.com/facebook/create-react-app/issues/11865
```
@deephaven/code-studio: ERROR in ./src/redux/actions.js 4:0-51
@deephaven/code-studio: Module not found: Error: Can't resolve './actionTypes' in '/home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/code-studio/src/redux'
@deephaven/code-studio: Did you mean 'actionTypes.js'?
@deephaven/code-studio: BREAKING CHANGE: The request './actionTypes' failed to resolve only because it was resolved as fully specified
@deephaven/code-studio: (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
@deephaven/code-studio: The extension in the request is mandatory for it to be fully specified.
@deephaven/code-studio: Add the extension to the request.
```

There are tons of these imports. Wait for the next patch? https://github.com/facebook/create-react-app/milestone/83

**Comment by mattrunyon** [comment]
https://github.com/facebook/create-react-app/issues/11756#issuecomment-1154197930 This is a workaround for the missing polyfills

Maybe we switch to vite though
