### ISSUE TITLE
CodeCov sometimes reports changes in ContextMenu

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#508]
CodeCov sometimes reports changes in ContextMenu even though it hasn't changed. An example PR: https://github.com/deephaven/web-client-ui/pull/506

The steps run seem to be in a `requestAnimationFrame` block: https://app.codecov.io/gh/deephaven/web-client-ui/compare/506/changes
It's possible the `requestAnimationFrame` is causing some indeterminate behaviour. Mock the `requestAnimationFrame` to provide certainty.

**Comment by dsmmcken** [comment]
Theory is that the raf in component did mount may or may not fire depending on how fast test runs
