### ISSUE TITLE
Replace anonymous useEffect functions with named functions

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#532]
For code cleanliness, we can replace all the anonymous functions we pass into our react hooks (such as `useEffect`) with named functions. This will help with code readability and debugging. See blog post discussing some of the benefits: https://laurenclark.io/posts/named-functions-vs-anonymous-arrow-functions/
Replace:
```
useEffect(() => {
  ...
}, []);
```
With:
```
useEffect(function myFunc() {
  ...
}, []);
```

There may be an eslint rule we can enable for this.

**Comment by dsmmcken** [comment]
what's the advantage of named vs anon here? does it help with debugging output or something?

**Comment by mofojed** [comment]
@dsmmcken Yes, this will help with debugging output but also code readability in general. See https://laurenclark.io/posts/named-functions-vs-anonymous-arrow-functions/ for a quick blog post showing the debug output.

**Comment by mofojed** [comment]
Good issue for Tony.
