### ISSUE TITLE
Frozen column double border on right edge does not touch top or bottom

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#556]
**Description**

There is a double border on the right edge of frozen columns. It is persistent when scrolled and ~~causes a gap in row hover/select styles~~ the hover/select styles go up to the right edge of the border

![image](https://user-images.githubusercontent.com/8619789/167030015-962ef76f-1c37-4df9-82a5-c2596c15eecf.png)

**Versions**
 - Deephaven: 0.11.8

**Comment by vbabich** [comment]
The double border on frozen columns is intentional, excel shows it as well.
The lack of hover styling on the frozen column is an issue though.
