### ISSUE TITLE
Sort and reverse bars are different heights

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#557]
**Description**

The sort and reverse header bars are different heights. This is mostly noticeable with side by side tables. 1 with a sort and 1 with a reverse.

It is slightly less noticeable with both applied

![image](https://user-images.githubusercontent.com/8619789/167032312-de37c9ea-072b-4c16-9fc2-928541ff4ff8.png)

![image](https://user-images.githubusercontent.com/8619789/167032349-6eadc283-5254-44d1-a32e-06a2f64f29fd.png)

**Versions**
 - Deephaven: 0.11.8

**Comment by dsmmcken** [comment]
This is as designed. Gives you a subtle visual difference that doesn't depend on just colour. You always want to show changes by more than just colour to be more accessible for colour blind. I do accept that this is a pretty subtle difference, and maybe a pattern or something would be even better.
