### ISSUE TITLE
Support for no console in the web UI.

### ISSUE THREAD

**Issue by niloc132** [deephaven/web-client-ui#596]
As an end user, I want to be able to turn off console access on the server, but still be able to use the web UI to browse dashboards, manipulate app mode tables.

To test this, set `deephaven.console.disable` to true on the server, and try to connect from the web UI.

Presently the web UI has an error if no console types are supported, and the tables cannot be used, nor the dashboard loaded.

**Comment by mofojed** [comment]
@niloc132 maybe a dumb question, but how/where do we set the `deephaven.console.disable`? Would that be defined in our docker-compose file or something?

**Comment by devinrsmith** [comment]
I think client could get this information from a "Web" ObjectType plugin. Potentially the same object as expressed in https://github.com/deephaven/web-client-ui/issues/703

**Comment by mofojed** [comment]
For this release, UI can check that `getConsoleTypes` returns an empty list, and just show an empty dashboard in that case.
We can work on general configuration for #703 later.

**Comment by mofojed** [comment]
@niloc132 right now the only end point to retrieve an object through the JS API is via [IdeSession.getObject](https://github.com/deephaven/deephaven-core/blob/124df76840da3eec950bebe77874f8af1ab3ec57/web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java#L109). With console disabled, we're unable to retrieve a session object.
Should I just expose `getObject` through `IdeConnection` as well? Might mean moving some of the logic into WorkerConnection (such as [IdeSession.getVariableDefintion](https://github.com/deephaven/deephaven-core/blob/124df76840da3eec950bebe77874f8af1ab3ec57/web/client-api/src/main/java/io/deephaven/ide/shared/IdeSession.java#L169))

**Comment by mofojed** [comment]
Blocked on https://github.com/deephaven/deephaven-core/issues/2779
