### ISSUE TITLE
sass watch is watching 100,000s of files

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#60]
**Steps to Reproduce**
1) Run `npm start` from the root directory
2) Check the number of watched files (from [StackOverflow](https://stackoverflow.com/a/60705427): `curl -s https://raw.githubusercontent.com/fatso83/dotfiles/master/utils/scripts/inotify-consumers | bash`)

**Expected Results**
2) Only the scss files in our src directories are watched

**Actual Results**
2) 100,000s of files are being watched... all of node_modules maybe?
```
    COUNT     PID USER     COMMAND
--------------------------------------
  104768   168748 bender   node /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/chart/node_modules/.bin/sass --load-path=../../node_module
  104243   168787 bender   node /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/iris-grid/node_modules/.bin/sass --load-path=../../node_mo
  103492   168876 bender   node /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/console/node_modules/.bin/sass --load-path=../../node_modu
   93774   168722 bender   node /home/bender/dev/deephaven/iris-oss/web-client-ui/main/packages/components/node_modules/.bin/sass --load-path=../../node_m

```

**Comment by mattrunyon** [comment]
https://github.com/sass/dart-sass/issues/1377
