### ISSUE TITLE
Full values of DateTimes should be more accessible

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#614]
It would be helpful if datetime columns had tooltips that showed the complete date and time:

![image](https://user-images.githubusercontent.com/9516585/173668983-b7bdeea4-e189-444c-89cd-2b2737511ddd.png)

**Comment by mofojed** [comment]
Moved the "Copy Cell Unformatted" to it's own ticket #919

**Comment by mofojed** [comment]
We do tooltips for URLs as a precedent.
```
from deephaven import empty_table
t = empty_table(100).update("x=`https://www.example.com/` + i")
```
