### ISSUE TITLE
Chart builder is broken

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#677]
Using the table sidebar menu, attempt to create a plot, after selecting options, plot fails to load with the following error

LogProxy.ts:82 [ChartPanel] handleLoadError TypeError: Cannot read properties of undefined (reading 'copy')
    at ChartModelFactory.js:47:35
    at c (runtime.js:63:40)

**Comment by mofojed** [comment]
Fixed with #693 in IrisGridPanel.tsx:
![image](https://user-images.githubusercontent.com/4505624/187696590-fb454328-33dc-4732-adfc-b56f4d3ef329.png)
