### ISSUE TITLE
Add support for clickable links

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#712]
As both a user and stakeholder, I'd be very interested in a new Markdown column type that can hold clickable links.  Basically, the column could show text like `Clink this link!` or `News article headline!`.  A user could hover their mouse over a cell, which would show the URL to which the link leads.  If the user clicks on a cell, it opens a new tab/window/whatever in the browser to take them there.

**Comment by devinrsmith** [comment]
I'm not sure we want a new column "type" - do we have a way to attach metadata to a column? @nbauernfeind @rcaudy?

Is this feature specifically targeted at supporting click-able links? Or, do we image a cell could contain a whole markdown document that could be opened and rendered?

**Comment by jjbrosnan** [comment]
The original intent of this PR is to support clickable links to the web.  However, if possible, the second option would be pretty awesome too.  That should likely be covered in a separate ticket.

**Comment by devinrsmith** [comment]
Some sort of metadata that allows client to know "this content is a URL" seems more appropriate than "markdown". Unless the intent is to make it "pretty" and support a "markdown" link syntax: `[pretty text](https://example.com)`.

**Comment by dsmmcken** [comment]
Not full markdown, but just `[pretty text](https://example.com)` might be nice for being able to have links that are labeled with text and not just an ugly url. Something to decide is the behaviour of the click which normally selects the cell. Particularly for cells that are part of an input table.

Google sheets approach is a zero-delay tooltip that displays this lovely popover. It fetches the page title, favicon and meta description for the link as well which is extra nice (would require a server side micro-service to do so). The link in the cell is not directly clickable as link, it still selects the cell for editing. The tooltip comes up immediately on cell hover, and the links it it are clickable. Links are auto-detected and can support arbitrary number of links per cell.
![image](https://user-images.githubusercontent.com/1576283/213721195-8723981a-f525-4c34-a184-324c52aeb4e5.png)

In contrast, excel only allows one link per cell, and the whole cell text will link to the first url given in a cell. Hovering the URL changes cursor, and clicking follows the link. The cell is still selectable if there is extra space to the right of the url in the cell and a few pixels at the top of the cell are also selectable. Additionally, you get this tooltip (with normal tooltip delay), stating "Click once to follow, click and hold to select cell" on hover. Ctrl+click/shift+click operations act as selections and not follow. 
![image](https://user-images.githubusercontent.com/1576283/213722288-1ccdbaa2-d6f3-4e70-8d96-6587e949eaea.png)

**Comment by dsmmcken** [comment]
- Direction: Excel style style for selection and clicking, tooltip with a similar text as excel. Test on both regular and input tables, where cells are selected individually, and user can enter a URL into a cell.
- Expect the we can detect multiple links, and hit box detection based on which one you click.
- Link detection should be automatic, and non-render blocking (maybe async if necessary or maybe just on the truncated value).
- Style link as $primary + underline, with cursor: pointer on cell hover.
- Links open in a new tab. 
- Soft requirement: expectation that it would work for multiple protocols, maybe a deephaven:// url could be useful for something? so don't detect just http(s)://

**Comment by emilyhuxng** [comment]
@dsmmcken What should be highlighted if a link is cut off? For example, 'github.co...'

**Comment by dsmmcken** [comment]
highlighted? Do you mean underlined? For underlining when there are ellipsis, the underline doesn't extend under the dots but does take the link color.

**Comment by emilyhuxng** [comment]
@dsmmcken For input tables, if a cell contains a link, should double click still edit the cell?

**Comment by dsmmcken** [comment]
> if a cell contains a link, should double click still edit the cell?

Good question. The first click would open a link in a new tab and would switch to that tab, blurring the original cell and exiting edit mode right? So that wouldn't work would it? Can you still detect the double click and cancel navigating to the link in that case?

Excel opens tabs into the background and also enters edit mode on a double click on a cell with a link, which we can really do because following the link browser steals focus into a new tab.

**Comment by dsmmcken** [comment]
> Should the tooltip show the full link or the truncated link?

Full

**Comment by emilyhuxng** [comment]
Yes, the first click opens the link. It might be possible if we add a tiny delay before processing the first mousedown event? 

> Excel opens tabs into the background and also enters edit mode on a double click on a cell with a link, which we can really do because following the link browser steals focus into a new tab.
Right, I looked it up and there isn't an elegant way to keep the focus on the current tab.

**Comment by dsmmcken** [comment]
I am not a fan of the delay approach.

Maybe we make the click hold behaviour enter select + enter edit mode if it's an input table?

**Comment by emilyhuxng** [comment]
Alright, I'll try that.
