### ISSUE TITLE
Download CSV function does not work in production build

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#763]
**Description**

The download CSV functionality does not seem to work in a production build. It does work in a dev build though.

**Steps to reproduce**
1. Start up deephaven-core and navigate to http://localhost:10000/ide/
2. Open a table or create a new table:
```
from deephaven import empty_table
t = empty_table(100).update(["x=i", "y=Math.sin(i)", "z=Math.cos(i)"])
```
3. Click on the menu button in the table and select Download CSV
4. Click the Download CSV button

**Expected results**
4. A CSV file is downloaded

**Actual results**
4. It says "Download complete", but no file is ever downloaded

In the browser logs, there is an error when it tries to download the file:
```
service worker setting table-2022-09-19-143606.csv download stream on service worker
14:56:18.350 LogProxy.ts:72 [TableSaver] start writing table, total snapshots:  1
14:56:18.351 serviceWorker.js:61 fetching... http://localhost:10000/ide/download/table-2022-09-19-143606.csv
14:56:18.356 TableSaver.tsx:651          GET http://localhost:10000/ide/download/table-2022-09-19-143606.csv 404 (Not Found)
```
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/4505624/191094236-e39ed24a-2f85-4b40-9bd6-b15244496662.png">

**Additional details and attachments**

**Versions**
 - Deephaven: v0.16.1
 - OS: macOS 12.6
 - Browser: Chrome Version 105.0.5195.125

**Comment by mattrunyon** [comment]
More helpful info about the service worker setup and potential issues #424

**Comment by mofojed** [comment]
Figured out what was going on with my machine. I still had a service worker registered against `/iriside/download`, and that was being found by DownloadServiceWorkerUtils. That issue was already identified with #424, and child issue #766 . I think this particular issue should be closed in favour of the other tickets.
