### ISSUE TITLE
Improve ColorUtils

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#765]
We should possibly move to something like chroma for color utils. Our current `ColorUtils.isDark` has poor performance because it does a dom manipulation

At least improve `isDark` and audit any other color utils we have to remove dom manipulations. Changing to a library would just give us more utils

**Comment by dsmmcken** [comment]
The colorjs.io package looks good lately as it supports CSS4 colors. Something I just remembered though is the enterprise "system badge" features accepts css variables as a value, so `var(--info)` (as a way of using system colors from iris.prop settings), which means it will always require getComputedStyle. However that could be broken into a separate function that system badge calls first.

That is until [color-contrast()](https://caniuse.com/mdn-css_types_color_color-contrast) css function ships (if ever).

**Comment by dsmmcken** [comment]
See my comment, I think we can WNI this.
