### ISSUE TITLE
Add engine version to settings, read other config settings

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#770]
In the settings panel, we currently show the UI version but not the engine version. These versions can be different. Will need some API support to get the engine version

**Comment by mofojed** [comment]
API ticket is https://github.com/deephaven/deephaven-core/issues/2668 (superceded https://github.com/deephaven/deephaven-core/issues/1616)

**Comment by mofojed** [comment]
@Zhou-Ziheng this will be similar to how we get the server config values on Enterprise. Take a look at [Login.jsx](https://gitlab.deephaven.io/illumon/iris/-/blob/rc/silverheels/web/client-ui/src/login/Login.jsx#L412) where we set the fetch the server config values and set them in redux, then in [SettingsMenu.jsx](https://gitlab.deephaven.io/illumon/iris/-/blob/rc/silverheels/web/client-ui/src/settings/SettingsMenu.jsx#L273) where we display the version information.

The PR that implemented the API community side was https://github.com/deephaven/deephaven-core/pull/2979. The biggest difference between Enterprise and Community is we'll need to retrieve the values from `dh.CoreClient`, which you can do after we initialize the client here: https://github.com/deephaven/web-client-ui/blob/c2f10a395058a78c527eb9e0e9750411279eebd2/packages/code-studio/src/main/AppInit.tsx#L192

The properties we care about are detailed in [Colin's comment](https://github.com/deephaven/deephaven-core/pull/2979#issue-1401668082), but basically `deephaven.version`, `java.version` are the main ones. We may want to change up how the versions are displayed (i.e. Only show the `deephaven.version`, have an info button for all the different lib versions? @dsmmcken may have some guidance).
