### ISSUE TITLE
User reports run button in notebook does not work with Safari

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#805]
Community slack user reports Safari run button was not executing code in safari. They were running latest/0.17.0

Investigate to confirm reproducibility. 

![Screen Shot 2022-10-10 at 5 00 55 PM](https://user-images.githubusercontent.com/1576283/195103287-12e1fc1a-a9be-4e34-81fe-9c1c974fd5c9.png)

**Comment by mattrunyon** [comment]
Confirmed in Safari 15.4 on Mac OS 12.3.1

Here's the error w/ source in dev (Safari dev tools doesn't copy the error message to my clipboard properly for some reason)

![image](https://user-images.githubusercontent.com/8619789/195152340-083ad077-366e-4cc7-9b26-4a8279c4315a.png)
