### ISSUE TITLE
GitHub action integration for running end-to-end/Playwright tests on each PR

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#825]

**Comment by mofojed** [comment]
We're having an issue where the web server is not fully started in the GitHub action. Looking at the Playwright startup code for waiting if the web server is available: https://github.com/microsoft/playwright/blob/9e91ca353c27cda89d16d2fff8ab270894866c0d/packages/playwright-test/src/plugins/webServerPlugin.ts#L137

If checking the port, it just checks if we're able to "connect": https://github.com/microsoft/playwright/blob/9e91ca353c27cda89d16d2fff8ab270894866c0d/packages/playwright-test/src/plugins/webServerPlugin.ts#L144

If checking the full URL, it checks for a success status code: https://github.com/microsoft/playwright/blob/9e91ca353c27cda89d16d2fff8ab270894866c0d/packages/playwright-test/src/plugins/webServerPlugin.ts#L159

Vite may still be building things when it starts the check? So it returns 200 for index.html, but then loading all the JS takes longer than 30s...

**Comment by dsmmcken** [comment]
Would increasing the webserver timeout be a dumb solution?

**Comment by mofojed** [comment]
> Would increasing the webserver timeout be a dumb solution?

We really only want to increase the web server timeout on the first test, but no it's not necessarily a dumb solution.

Jason and I figured it out - just the initial load is taking ~32s when using Vite in dev mode (npm start, which loads all CSS/tsx files separately instead of bundling), but then after that all subsequent tests are quick (as all files are cached). So just increasing the timeout of the first page load has it working successfully.
Trying with vite preview as suggested by Matt (`npm run preview`) which uses a production build of the app cuts initial page load to ~3s, and it looks like any future page load is ~1-2s faster (note just loading the page, not the actual running of the test).
Breaking it down in GitHub actions, [with preview](https://github.com/mofojed/web-client-ui/actions/runs/3566853393/jobs/5993814633) it takes 2min to run all the tests, but has the overhead of a 3min build; [with start](https://github.com/mofojed/web-client-ui/actions/runs/3566617252/jobs/5993290230) it takes just under 3min (about 1 min longer; breaking it down to ~30s for initial page load, then an additional 1-2s for each of the 12 page loads triggering) to run all the tests, but there's no build step (so 0min build). Overall, it took 5m26s for start, 7m56s for preview (due to build overhead).

Build is ~3min, so we'd need roughly 75 page loads within our tests before running with `vite preview` with a production build is consistently quicker than just doing an `npm start`. We need to do a production build with the flag `VITE_CORE_API_URL=http://localhost:10000/jsapi` set so that it loads the JS API correctly. We already are doing one production build in node.js.yml that doesn't have that flag, but perhaps we can just add the flag there (since we're not actually publishing that build, we're just doing it to make sure it builds successfully) and then there isn't really any extra overhead with doing the build, we can use `npm run preview:app`, and decrease the timeouts.
