### ISSUE TITLE
Cell overflow viewer with browser zoom is scaled incorrectly

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#834]
1. Add 150% browser zoom
2. Click the view contents button on a cell with many lines of overflow

Expected: overflow modal is full height, shows all the contents
Actual: overflow modal is incorrectly sized, really short. Toggling the line number triggers it re-draw and show correctly.

![image](https://user-images.githubusercontent.com/1576283/197058363-ca848333-489f-4e51-8157-bbdb6d3cc9cf.png)

**Comment by emilyhuxng** [comment]
Here is a code segment to run an example: 
```
from deephaven import new_table
from deephaven.column import string_col, char_col, int_col
import random
import string

letters = string.printable
strings = [''.join(random.choice(letters) for i in range(random.randint(0, 10000))) for j in range(0, 1000)]
table1 = new_table([string_col("Random", strings)])

table2 = new_table([
    string_col("Short", ["A" , "B", "C", "D"]),
    string_col("Long", ["A"*50 , "B"*500, "C"*5000, "D"*49900]),
    char_col("Char", "ABCD"),
    int_col("Int", [123456789, 234567890, 42, 8675309])
])

json = new_table([
    string_col("JSON", ['{"test": "prop", "a": true, "b": 13}']),
])
```

**Comment by mattrunyon** [comment]
Note this only applies to items with very long lines. The json/random multiline text does not have the issue
