### ISSUE TITLE
Add an option for word wrap in code editing panels

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#845]
In the notebook panel overflow menu add an option for toggling word wrap of the monaco editor (off by default). Setting is per panel.

![image](https://user-images.githubusercontent.com/1576283/198073232-4e6ee10c-ddf1-4015-9ca2-b413246ca9f4.png)

We don't have any global configuration of monaco settings at this time.

Request by a community user in slack.

**Comment by dsmmcken** [comment]
Note you could consider assigning and exposing "alt+z" as shortcut as per vs code -- check mac shortcut in vs code for parity.

**Comment by hhashim1** [comment]
Any updates on this feature?
