### ISSUE TITLE
Option to increase information density

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#885]
As a power user, I want increase the information density to allow for more information to appear on the screen at once. Things like reducing column/row padding in grids, decreasing font size, decreasing padding in plots, decreasing tab padding/size, etc.

**Comment by dsmmcken** [comment]
We default slightly higher in font-size and in cell y-padding, and marginally higher in x-padding. A higher density option that lowers font-size and padding would increase density, we should also offer the reverse.

![image](https://user-images.githubusercontent.com/1576283/201960015-37e7bac3-be44-4dfc-909b-bb104f3bbc76.png)

**Comment by dsmmcken** [comment]
In terms of just the table:
![image](https://user-images.githubusercontent.com/1576283/201962643-499e7c67-d3f6-4935-9d21-c984c1a3d083.png)

1px taller text, and overall cell height is 3px taller per cell. 

Horizontally it's mixed, some cells are wider by default some are narrower, but padding is still larger. Overall though we come out slightly wider.
![image](https://user-images.githubusercontent.com/1576283/201964060-55edabba-164f-42c8-9bd6-11ed9c59b52c.png)

**Comment by dsmmcken** [comment]
In practice, on a fresh console running a single command, we are showing 6 rows less than swing. We lose a bit of space from browser chrome, but also we are proportionally allocating more space to the console (we have less ui-chrome in the console panel). So we could reduce it's default height and still be comparable. Currently it's 50/50 split, but maybe 40/60 or something would be a better default. Our tabs are slightly taller, and so are out header columns, but I think there's value in that in terms of click target size and would prefer to squeeze elsewhere.

![ui-chrome-comparison](https://user-images.githubusercontent.com/1576283/201971597-bbca0c4d-2233-4e87-bfec-494bc2947d3f.jpg)

**Comment by rbasralian** [comment]
Just adding another example to this:

![image](https://user-images.githubusercontent.com/9516585/232853952-d4b172a6-39ec-47b5-919e-62fc65ae9e1e.png)

![image](https://user-images.githubusercontent.com/9516585/232854011-83fb9964-abcf-4553-a4fb-09965a55ed25.png)

These two screenshots were taken w/ the boundaries between the charts/tables exactly lined up, more or less to the pixel.

Here is the second screenshot again, with font size increased to 12:

![image](https://user-images.githubusercontent.com/9516585/232854513-2e1e94e9-dc3a-4491-bc26-f8b33d80193b.png)


This give me a few thoughts:

- The web UI should let users change the table header/text font sizes.
- The web should support 'auto resize all columns' like Swing does, which should make the column widths fit the headers very tightly, so more columns fit on screen. (I think the Swing rule is that it the header or the data, whichever is wider, up to some reasonable max # of pixels.)
- The web plots are wasting a decent amount of space below the plot.
- The column headers could probably have a bit less padding on top/bottom.

**Comment by dsmmcken** [comment]
That's useful feedback. Thanks for the screenshots.

>the header or the data, whichever is wider
We have the same logic. I think we are too zealous with the horizontal padding on the headers, which combined with the font-size difference probably accounts for most of the horizontal difference.

> The web plots are wasting a decent amount of space below the plot.
Possibly reserving space for the x-axis label even though none is set?

> The column headers could probably have a bit less padding on top/bottom.
This is one spot I think the extra couple vertical pixels are worth spending, as the headers act as buttons. The sort/reverse indicator bars also use this reserved space. We should shave it everywhere else though.
