### ISSUE TITLE
Trying to type in one panel in focus, but text goes to another panel

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#912]
**Description**
Reported from Community: https://deephavencommunity.slack.com/archives/C036HT73T43/p1668809621737029?thread_ts=1668804780.460239&cid=C036HT73T43
> I think its in the latest version 0.17.0, or maybe even one before I have issues typing where I will be typing in a panel however my text ends up going in some other panel that is not visible. I have messed up a lot of my code that way.  I have to select different random panels and then come back to be able to type or sometimes refresh the browser then my typing will show up in the panel I am supposed to be in.  This non-typing issue typically shows up when I start the server for the first time in the day or after a restart sometimes.

**Versions**
 - Deephaven: v0.17.0
 - OS: Windows
 - Browser: Chrome

**Comment by hhashim1** [comment]
The editor issue is almost every time that it has become a nuisance for me. Almost every time when I restart or refresh the browser...some of the code in some random tab...in most cases its in one of the tabs that I have been recently working in...

Most of the times it will add a random block of code of parenthesis at the end of the file but sometimes some of the latest code will get deleted or partially deleted.

**Comment by vbabich** [comment]
We haven't been able to reproduce this internally. Closing as not reproducible.
@hhashim1 if you observe this issue again, feel free to reopen this ticket.
