### ISSUE TITLE
Double clicking a file causes the loader to flash incorrectly

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#942]
**Description**

Double clicking a file that is not open causes it to briefly open in preview mode and then in full mode. The loading spinner double flashes in and out on the panel that is opening.

Double clicking a file that is open in preview mode triggers a load as well. This shouldn't happen since the file is already open

**Steps to reproduce**
1. Open a code studio
2. Double click in the file explorer on a file that is not currently open
3. Single click a file that is not open so it opens in preview mode
4. Double click the file that is open in preview mode

**Expected results**

2. The first file opens in full mode w/ 1 loading spinner and no flashes
4. The second file opens in full mode with no loading spinner

**Actual results**

2. The first file opens in preview mode w/ loading spinner, displays file, then loading spinner again, then file in full mode
4. The second file opens in full mode after a loading spinner

**Versions**
 - Deephaven UI: 0.22.2

**Comment by dsmmcken** [comment]
This is pervasive throughout the app, you can double click a whole lot of things and cause problems.

**Comment by mofojed** [comment]
> This is pervasive throughout the app, you can double click a whole lot of things and cause problems.

I don't think that really applies in this situation. In this case, a double-click is _supposed_ to do something specific.

We're essentially simulating the same behaviour as VSCode; single click opens a file in "preview" (italics in the title bar), and then double-clicking it opens it "non-preview" (regular styling in title bar). Basically after doing a double-click, the content shouldn't change at all, it should just be the title-bar that is re-opening. I imagine what we're currently doing is replacing the whole tab, causing the file to reload. Should handle that differently.
