### ISSUE TITLE
Cancelled promises do not reject until original promise resolves

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#949]
**Description**

When you call `cancellablePromise.cancel()`, the promise does not reject immediately. Instead, we wait for the original promise that was wrapped to resolve/reject and only then do we reject the promise. If calling cancel, we shouldn't care about the original promise any more, so we should just discard it and reject our cancellable promise

Also, you cannot do `PromiseUtils.makeCancelable(something).then().catch()` and still call cancel. You have to create the promise in 1 statement and add then/catch in another. Might be a nice thing to cleanup as well

**Steps to reproduce**
```ts
import { PromiseUtils } from '@deephaven/utils';

const a = new Promise((resolve, reject) => {
  setTimeout(() => resolve(), 120 * 1000); // 2 minutes until promise resolves
});

/* This syntax doesn't actually work, but it should. Cancel gets removed
const b = PromiseUtils.makeCancelable(a)
  .then(() => console.log('resolved'))
  .catch(() => console.log('rejected'));

b.cancel();
*/

const b = PromiseUtils.makeCancelable(a);
b.then(() => console.log('resolved')).catch(() => console.log('rejected'));

b.cancel();
```

**Expected results**

Logs rejected immediately

**Actual results**

Logs rejected after 2 minutes

**Versions**
 - Web UI Version: 0.22.2

**Comment by mofojed** [comment]
This might be a good one to go through with Emily.

**Comment by emilyhuxng** [comment]
About the promise chaining, should the .then block and .catch blocks return a cancellablePromise? For now, I only addressed the immediate cancellation.

**Comment by mattrunyon** [comment]
If you're talking about `const a = PromiseUtils.makeCancelable(something).then()`, then yes it should return a cancelable promise I think. So we would need to add a `then` and `catch`, and `finally` (for good measure) to the wrapped promise.

@mofojed what are your thoughts? The TS around it is correct at least so if you try to do the above chain and then call `a.cancel()`, it isn't allowed since `a` is a regular Promise.

**Comment by mofojed** [comment]
Keep this PR for immediate cancelation.

For cancelation chaining, I thought there may be complications in the .catch place, but I may not have thought it all the way through.

**Comment by mofojed** [comment]
How would the cleanup function work for a chained cancelable promise? 
I think it's best to just require calling `makeCancelable` again if you want the chained result to also be cancelable...
