### ISSUE TITLE
Make redefined shortcuts work in Monaco

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#95]
Currently within the script editor we use Monaco's `addAction` to define the Run and Run Selected shortcuts.  As a result, changing those shortcuts doesn't actually work. Figure out how to adjust those to change with the shortcuts when a user changes these shortcuts.

Steps to reproduce
1. Change the notebook shortcut for "Run" or "Run all"

Expected
2. The new shortcut works within the notebook.

Actual
2. The new shortcut does not work within the notebook. Only the default shortcut will ever work.

Until this is fixed, those shortcuts will be marked as not editable by users

**Comment by nbauernfeind** [comment]
@mattrunyon Does this apply to `Console - Clear` too? I could not use that after a remap either. Also, can I suggest renaming this to `Console - Clear Input` -- Specifically I would expect the "Console" to be cleared not the input box itself based on the title of the shortcut.
