### ISSUE TITLE
Create a Dockerfile to update e2e snapshots

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#960]
Right now the instructions to update Playwright snapshots for use in CI are cumbersome. Create a Dockerfile that encapsulates all the steps and makes it easy to do.

**Comment by mofojed** [comment]
Getting an error right now when trying to run all the tests and update snapshots: https://github.com/microsoft/playwright/issues/17876
Looks like it's targeted for a fix in Playwright v1.30. May delay this fix until that is completed...

**Comment by mofojed** [comment]
https://github.com/microsoft/playwright/discussions/13716

**Comment by wxiaoguang** [comment]
> Getting an error right now when trying to run all the tests and update snapshots: [microsoft/playwright#17876](https://github.com/microsoft/playwright/issues/17876) Looks like it's targeted for a fix in Playwright v1.30. May delay this fix until that is completed...

Do you mean you can also reproduce it?

**Comment by mofojed** [comment]
@wxiaoguang I could on the 1.28 image, but seems to be working fine now in 1.30. Not sure if it was the playwright update, or an update to docker, or what but seems to be fine now.

**Comment by wxiaoguang** [comment]
At the moment I can not reproduce it from my side either. Maybe it has been fixed somehow 😂
