### ISSUE TITLE
Remove uses of JS API column index

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/web-client-ui#965]
`Column.index` is deprecated in JS API and Colin would like to remove it since web is the only place still using it

Within the TS files, I only see it in 2 places. You can remove the field in `dh.types` and then run the type checker to find the uses.

```
TableUtils.ts
IrisGridUtils.ts
```

Alternatively, can add an eslint plugin like https://www.npmjs.com/package/eslint-plugin-deprecation

**Comment by bmingles** [comment]
@mattrunyon Are there any specific features I should regression test to make sure I don't break anything?

**Comment by mattrunyon** [comment]
Nothing off the top of my head, but I see there's no tests for `TableUtils.getSortIndex`, so I would look into how that's used and write some tests first maybe. The only other place I see it used is `IrisGridUtils.dehydrateSort`, so it looks like the related features would just be applying sorts and reloading the page to ensure the sorts saved and restored correctly
