### ISSUE TITLE
Append-only input tables don't properly add data if you attempt to modify a pre-existing row

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#990]
**Description**

Attempting to modify a cell in an append-only input table results in the new data being written twice.

**Steps to reproduce**

Create an append-only input table.

```python
from deephaven import InputTable
from deephaven import empty_table

t = empty_table(10).update(["X = i"])
t2 = InputTable(init_table=t)
```

Then, attempt to modify a pre-existing cell. Hit enter (or the commit button), and the new data will be written twice to the bottom of the column.

**Expected results**

I expect one of two things to happen:

- To not be able to type in the cell
- My data gets written to the end of the table once.

**Actual results**

The data is entered into the table twice. There was an instance where I found that `table.size` reported one less row than what the UI shows. I have yet to repro that.

**Additional details and attachments**

**Versions**

 - Engine Version: 0.19 (latest)
 - Web UI Version: latest
 - Java Version: 11
 - Barrage Version: unsure
 - OS: OS X Catalina
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by mofojed** [comment]
We should not be able to edit existing rows in append-only tables.

Should be able to enforce this behaviour in [IrisGridTableModelTemplate.isEditableRange](https://github.com/deephaven/web-client-ui/blob/main/packages/iris-grid/src/IrisGridTableModelTemplate.ts#L1544), checking if the table has any key columns, only allowing pendingRow changes if it doesn't.
