### ISSUE TITLE
The UI shows a scroll bar for individual cells in input tables

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#991]
**Description**

A scroll bar is present on the right hand side of a cell in an input table while data is being entered.

**Steps to reproduce**

Create an input table and enter data.

```python
from deephaven import empty_table, InputTable

t = empty_table(10).update(["X = i"])
t2 = InputTable(t)
```

Then, add data to a table, and on the right hand side, a small block appears. It's a scroll bar, and you can slightly move the text up and down.

**Expected results**

No scroll bar.

**Actual results**

A scroll bar.

**Additional details and attachments**

**Versions**

 - Engine Version: 0.19 (latest)
 - Web UI Version: latest
 - Java Version: 11
 - Barrage Version: unknown
 - OS: OS X Catalina
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by jjbrosnan** [comment]
![InputTable_ScrollBar](https://user-images.githubusercontent.com/84038776/212077663-f2c93e95-e7b1-4c01-bc1c-e669a7eaab46.gif)

**Comment by bmingles** [comment]
@jjbrosnan this seems to be behaving correctly. No scrollbar with single line for me. Scrollbar appears once multi-lines are used. Can you see if you are still able to produce?

**Comment by bmingles** [comment]
I can't reproduce this.
